---
title: "Final Project Overview"
author: "NRES 746"
date: "Fall 2025"
output: 
  html_document: 
    theme: cerulean
    toc: no
    toc_float: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


## Group projects: expectations

Students are expected to perform (and write up the results for) a data analysis using *a custom model-based analysis using maximum likelihood or Bayesian inference*. The write-up will loosely take the format of a scientific paper to be submitted to a professional journal. However, because of the nature of this course, the most important pieces of the write-up are the **methods** and **results** sections. Nonetheless, I expect at least a few paragraphs introducing the topic and why it's important, and a few paragraphs discussing the implications of the results. The methods and results section can (and in many cases should) be much longer than you typically see in a scientific paper- don't feel constrained by space for these sections! Not that you need to be wordy, I just want to make sure you have the space to clearly explain the analyses you performed and why you made the choices you did!

Here is a more detailed description of expectations for the final group project:

**Introduction:** Provide enough description so that the reader understands why the research is important and what research question(s) and/or hypotheses are being addressed. The importance and novelty of the research should be clear after reading this section, and the reader should be able to identify (1) the study system, (2) the intellectual context (what previous work and conceptual frameworks motivated the study?), (3) the current knowledge limits that your study addresses, and (4) one or more testable research questions (at least 3 paragraphs). The research questions/hypotheses should be presented at the end of the Introduction.  

**Methods:**      

* Provide just enough details about the data collection to give the reader the context necessary to understand the data (what, where, when, how).     
* Provide plenty of detail about the analytical approach- enough detail to fully replicate the analysis. Justify all decisions that were made and (where appropriate) discuss why you did not use alternative approaches.   
* Discuss key assumptions.  
* Use equations where appropriate!    
NOTE: This section can be longer than the methods section of a standard manuscript. Make sure you include citations for all R packages and analytical methods used. 

**Results:** Present all relevant results completely and concisely. Wherever possible, results should be presented via figures and tables. There is a limit of 8 figures and tables (max of 5 figures and 3 tables), so choose carefully which figures and tables to present. Figures should be *publication quality*. Include code for generating your figures in your project GitHub repository (see below).     

**Discussion:** Write at least three paragraphs that put the results in a larger context (returning to the research questions/hypotheses) and discuss areas of uncertainty. Potential topics are possible violations of assumptions, and future work that your analysis suggests would be profitable.

**GitHub Repository Link** Put all code used to run the analyses and produce the figures/tables -- and ideally the raw data you used -- in a GitHub Repository, and provide the link to this repository.

**Acknowledgements**  Please acknowledge those who collected the data, assisted with obtaining data, analyzing data, etc. 

**Literature cited**  (of course, no explanation needed!). Use a clear and consistent format.        

## Picking a topic

Your final project should not be part of your thesis. That said, there is no requirement that your final project is not *relevant* to your graduate thesis project. You will end up spending quite a bit of time on your final projects, so think about what types of analyses you want/need to get to know better- ideally something that may strengthen your thesis project. 

## Picking a dataset

You are not required to use a public dataset, but there are lots of great datasets out there... see [links page](Links.html#Data_links). You might talk to your advisor to see if they have any data sets they might be willing to let you use. Remember that many previous projects in this class have resulted in publications, so you might want to make sure you have permission to publish your analyses of this data set.

#### Group project overview (1-2 pages)  

Please provide a 1-2 page project description ("proposal"). Make sure you include:     

* Project title     
* Participant names      
* Brief background (motivation for research question)     
* Research question(s) (and hypothesis if applicable)     
* Primary and ancillary data sources (brief description of what the dataset comprises and how much there is)      
* Anticipated analytical approach(es) (just a first stab, no problem if this changes)    

See WebCampus for deadline. 

## Group project oral presentations

Each group will have 15 minutes allotted for group presentations, with a few minutes for questions. 

Sign up for a presentation slot using our class sign-up sheet using Google Sheets (see WebCampus)

A simple presentation rubric can be found [here](Presentation rubric.docx)

Please upload a copy of your final presentation by the deadline specified on WebCampus.

## Group project rough draft

See WebCampus for deadline. 

## Group project final paper

See WebCampus for deadline. 




















