---
title: 'Welcome to NRES 746'
author: "Advanced Analysis Methods in Natural Resources and Environmental Science"
date: "August 22, 2016"
output: 
  html_document: 
    theme: cerulean
    toc: yes
    toc_float: yes
---
  
      
###Instructor 
Kevin Shoemaker			
Office: FA 220E					
Phone: (775)682-7449					
Email: [kshoemaker@cabnr.unr.edu](kshoemaker@cabnr.unr.edu)			
Office hours by appointment. 

### Course Meeting Times
**Lecture & Discussion**: M, W at 10am (50 mins)  
**Lab**: Th at 1pm (3 hours)  
Lectures will be held in SEM 257   
Labs will be held in the NRES computer lab (FA 234)

### Course Website
[kevintshoemaker.github.io/NRES-746](https://kevintshoemaker.github.io/NRES-746)

###Course Objectives
Modern computers have reduced or eliminated many of the barriers to advanced data analysis, and as a result computational algorithms now often have primacy over elegant and simple mathematical formulae for complex data analysis. Armed with basic concepts of probability and statistics, and with some facility with computer programming, ecologists and natural resource professionals can get more out of their data than ever before by using or developing algorithms that can account for biological realities that would have been ignored under traditional statistical models. **In this course, we fully accept and embrace the primacy of the algorithm**.  

By the end of this course, students should have the ability to program simple algorithms and make use of a wide variety of more complex data analysis algorithms. The goal is for students to emerge from this course as creative data analysts with the tools needed to make sense of a wide variety of data types. 
**The course motto**: *Be Dangerous*!   

The focus of this course is on using computational models to infer ecological processes and relationships from pattern in observational studies; *we will not directly address experimental methods or design in this course*. However, the data analysis methods covered will be of broad utility for a wide variety of disciplines. The general focus will be predictive statistical modeling methods, including regression-based approaches, hierarchical and mixed models, multi-model inference, ensemble methods, maximum entropy models, classification and regression trees, random forest, and structural equation modeling, and geographic models of species distributions. Note also that *this is not a "statistics" course per se*; we will focus on the implementation and leave the nitty-gritty stats questions to statisticians (or more often textbooks written by statisticians).  

This course is an advanced graduate seminar, and will strongly feature *student-led discussions*. Instructor-led lectures will be kept to a minimum, and each student will be responsible for leading discussions on data analysis methods and results. The laboratory portion of the class will provide students the opportunity to try out some of the data analysis methods. Structured labs with example data sets will be interspersed with open lab periods where students work in small groups on a research project involving analysis of a real-world data set. 

### Student Learning Objectives
1. Identify and contrast the major classes of statistical models used by ecologists (e.g., Bayesian vs frequentist, likelihood-based, machine learning) and explain how and why ecologists use these models. 
2. Apply advanced analysis tools such as Generalized Linear Models (GLM), Bayesian inference, and Random Forest (RF) on diverse data sets representative of those commonly considered in observational studies in ecology.
3. Learn to explore data sets quantitatively and graphically and to prepare data appropriately for analysis. 
4. Perform statistical analysis, data visualization, simulation modeling, model validation and basic programming with the statistical computing language R.
5. Critically evaluate the strength of inferences drawn from statistical models by understanding and testing major assumptions and using tools such as cross-validation.
6. Communicate statistical concepts by leading lectures and discussion on advanced topics in data analysis.

### Prerequisites
Curious scientific mind, broad research interests, comfort with (or at least, lack of fear regarding) quantitative topics and basic mathematics. Students are expected to already have a fundamental knowledge of relevant statistical methods, obtained through other coursework. If this is not the case, they should be prepared to work harder to develop the necessary prerequisite knowledge.

### Textbooks and Readings
We will use the book, [Ecological Models and Data in R](https://ms.mcmaster.ca/~bolker/emdbook/), by Ben Bolker, as a general class reference. However, numerous readings will be assigned, and will be available on the course website.   
In addition, readings will be assigned as indicated in the course schedule and bibliography (which is rapidly evoliving!). For the discussions for which they will be responsible for leading, students will be able, with the instructor's permission, to substitute readings of their own choice for the "default" ones suggested by the instructor. 

### Grading
|Course component           | Weight                                  |
|---------------------------|-----------------------------------------|
|Student-led presentations  |	20%                                     |
|Class Participation        |	20%                                     |
|Short Laboratory Reports	  | 20%                                     |
|Research Project		        | 40% (30% manuscript, 10% presentation)  |

### Course components

**Student-led presentations**: Each student will be responsible for leading two class lectures/discussions that introduce a data analysis method using a worked example, and discuss applications of the method from the published literature. Presenters are encouraged to work with the instructor to better understand their data, methods, papers and topics. Additional instructions for lecture/discussion leaders will be handed out early in the semester.  
**Class Participation**: Students are expected to actively participate in the classroom education process, particularly during student-led lecture/discussions. Each class discussion period, the instructor will rank on a 1 - 5 scale the level of each student's participation. Students will be judged both on quantity and quality of their participation.  
**Laboratory Reports**: Students will submit a brief report summarizing each laboratory activity, succinctly answering any questions posed, and stating any questions or uncertainties the students would like the instructor to address. While students will work on the labs in small groups, individual lab reports will be submitted.   
**Group Projects**: Students will work on projects in groups of 2 - 3 people. Projects will require analysis of previously published or new, publicly available data sets that are NOT intended to be part of a student's planned thesis or dissertation chapters. The instructor can assist with identifying suitable data sets. Although a primary goal is to enhance knowledge and facility with the data analysis methods, an important secondary goal could be to develop a collaborative manuscript for peer-reviewed publication! Therefore, careful thought should go into choice of a data set and relevant scientific questions to guide the analysis. 
The group project will take the form of a manuscript in a specified journal format, suitable for submission as a research paper. This will be submitted to the instructor as a complete draft by [TBD], and (after review and comment by the instructor) as a final version by [TBD]. 

### [Course Schedule](https://kevintshoemaker.github.io/NRES-746/schedule)  
  
### [Lab Schedule](https://kevintshoemaker.github.io/NRES-746/labschedule)    

### Disability Statement  
Any student with a disability needing academic adjustments or accommodations is requested to speak with me or the Disability Resource Center (Thompson Building Suite 101), as soon as possible to arrange for appropriate accommodations.

### Academic Standards
The University of Nevada, Reno has established regulations for student conduct, including policies related to academic standards and academic dishonesty (see UNR 2010-2011). This includes but is not limited to plagiarism and cheating. As a student enrolled in this class, you are accountable to these policies and regulations. Per the catalog:

#### *Sanctions for violations of academic standards may include the following*:
1.	Canceling a student’s enrollment in the class without a grade  
2.	Filing a final grade of “F”  
3.	Awarding a failing mark on a test or paper in question  
4.	Requiring the student to retake the test or resubmit the paper”  

### Statement on A/V Recording
“Surreptitious or covert video-taping of class or unauthorized audio recording of class is prohibited by law and by Board of Regents policy.  This class may be videotaped or audio recorded only with the written permission of the instructor.   In order to accommodate students with disabilities, some students may be given permission to record class lectures and discussions.  Therefore, students should understand that their comments during class may be recorded.”





