---
title: "Intro to NRES 746"
author: "Welcome!"
output: 
  html_document: 
    theme: cerulean
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In this class we will survey a broad range of data analysis methods, with a focus on developing custom algorithms for solving non-standard problems (which in ecology and natural resources management means most problems!).

## Syllabus:
First let's take a walk through the online syllabus:

[Link to syllabus](index.html)

## Making up classes and labs
Many of you have already informed me you will need to miss some lab or class periods for various valid reasons, such as field work. Course materials and laboratory exercises will be posted online in enough detail to complete on your own. That said, much of the benefit of this course will come from interactions with peers and the instructor during class and lab periods and I expect you to do your best to attend and participate wherever possible!  

## Textbook
Please order the course textbook (Ecological Modeling and Data in R, by Ben Bolker) as soon as possible. You can purchase the textbook on [Amazon](https://www.amazon.com/Ecological-Models-Data-Benjamin-Bolker/dp/0691125228). All other readings will be posted on WebCampus.  

## Learning R
All of you should have R and RStudio installed on your computers. See the [links page](https://kevintshoemaker.github.io/NRES-746/) for some useful references. I will be leading ["bootcamps" on using R](https://kevintshoemaker.github.io/R-Bootcamp/index.html) in two upcoming Saturday afternoons (TBD)- please consider attending if you don't have much experience in R!

## ["stats chats"](https://guides.library.unr.edu/StatsChats)
The UNR Research Data Services program hosts informal weekly sessions for grad students and faculty to discuss data analysis questions. This can be a good opportunity to ask questions, find out more about what types of data and questions your peers are working with, and contribute some insights!  

## Student led topics
Use the Google Sheets link to sign up for a topic and a date. Once you have selected a topic, please move your topic to the "Topic" column and use a strikethrough in the "Unused topics" list to indicate the topic is taken!  

See WebCampus for Google Sheets link for this class

## Introductions
Let's take some time go around the room and introduce each other and what we are hoping to get out of this course. 

Please take the time to introduce yourself in more detail on the ["WebCampus" site](https://unr.canvaslms.com/courses/45665) -- I posted a question on the discussion board, which some of you have already responded to...  

Remember, I need your frequent and honest feedback in order to make sure that the level is appropriate and the topics are useful!





