---
title: "Lab Exercise 2"
author: "NRES 746"
date: "September 9, 2016"
output: 
  html_document: 
    theme: cerulean
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Publicly available datasets, potentially for final project...  (many links courtesy Tom Langen) 

### GOVERNMENT AGENCY DATA PORTALS 

[National Atlas](http://www.nationalatlas.gov/) (Geospatial data on the environment, economy, and people of the US).   

[US Department of Agriculture Census of Agricultural Data](http://www.agcensus.usda.gov/) (Authoritative data on all aspects of agriculture in the US.)      

[Center for Disease Control & Prevention Data & Statistics](http://www.cdc.gov/datastatistics/) (Comprehensive data on all aspects of disease epidemiology.)     

[USGS Water Data for the Nation](http://waterdata.usgs.gov/nwis) (Hydrological and water-quality data from across the US.)     

[EPA Wadeable Stream Assessment](http://water.epa.gov/type/rsl/monitoring/streamsurvey/web_data.cfm)(Downloadable data on a national survey of stream water quality)   

[USGS Survey Disease Maps](http://diseasemaps.usgs.gov/index.html) (US County-scale maps of incidence patterns of various mosquito-vectored diseases)    

[The Multi-resolution Land Characteristics Consortium (MRLC) National Land Cover Database](http://www.mrlc.gov/) (Land cover or land use, canopy cover, and impermeable surface area of the entire US, at a resolution of 30 m x 30 m, based on remote sensing data from satellite imagery.)  

[US Fish & Wildlife Service National Wetlands Inventory](http://www.fws.gov/wetlands/) (Wetlands greater than 1 acre are mapped and classified throughout the US, Puerto Rico and US territories. Data can be examined using the [Wetland Mapper](http://www.fws.gov/wetlands/Data/Mapper.html) and then downloaded for use by a GIS application, or can by inspected directly using [Google Earth](http://www.fws.gov/wetlands/Data/GoogleEarth.html))   

[USDA Forest Inventory and Analysis National Program](http://fia.fs.fed.us/) 
[Forest Inventory Data Online (FIDO)](http://fia.fs.fed.us/tools-data/default.asp) (Highly-detailed periodic surveys of forest composition at sites throughout the US.)   

[US Geological Survey](http://www.usgs.gov/) (Reports, data analysis, maps, and raw data on a diversity of topics related to environmental science, including biodiversity and emerging diseases.)

[NOAA National Climate Data Center](http://www.ncdc.noaa.gov/oa/ncdc.html) (Extensive data archives of climate data, including paleoclimate.)

### ENVIRONMENTAL DATA CLEARINGHOUSES
[Ecotrends](http://www.ecotrends.info/EcoTrends/) (Data archive and data visualization tools for ecological data at sites distributed around the US.)  

[NASA Global Change Master Directory](http://gcmd.nasa.gov/index.html) (Data on all aspects of global change, includes data on climate, land use, biodiversity and human dimensions.)  

[Oak Ridge National Laboratory Distributed Active Archive Center for Biogeochemical Dynamics(ORNL DAAC)](http://daac.ornl.gov/index.shtml) (A NASA-sponsored source for biogeochemical and ecological data and models useful in environmental research.)  

[Pole to Pole Ecological Research Lattice of Sites (P2ERLS)](http://www.p2erls.net/) (Portal to research stations and research networks, including their data archives.)  

[Weatherspark](http://weatherspark.com/) (Visualized time-series data on local climate at sites around the globe.)  

[Long Term Ecological Research (LTER) Network](http://www.lternet.edu/) (Network of research stations that have standardized monitoring programs as well as site-specific research. Sites are mandated to make data publicly available on the web.)  

### BIODIVERSITY DATA CLEARINGHOUSES /ARCHIVES
[International Union for the Conservation of Nature (IUCN) Redlist](http://www.iucnredlist.org/) (Searchable list of the world’s threatened and endangered plants and animal species on the IUCN Redlist.)  

[Conservation International Global Biodiversity Hotspots](http://www.biodiversityhotspots.org/Pages/default.aspx) (Detailed data on the attributes and threats to the world’s global biodiversity hotspots.)  

[National Biological Information Infrastructure](http://www.nbii.gov/) (Data archive and clearinghouse for biological data from the US. Also provides standards for metadata.)  

[Biological Inventories of the World’s Protected Areas](http://www.ice.ucdavis.edu/bioinventory/bioinventory.html) (Searchable species occurrence records and species lists for over 1,400 protected areas around the globe.)  

[Global Biodiversity Information Facility](http://data.gbif.org/welcome.htm) (An enormous clearinghouse of biodiversity data) 

[Global Population Dynamics Data Base](http://www3.imperial.ac.uk/cpb/research/patternsandprocesses/gpdd) (5000 population size time series for 1400 species, most of which have at least ten years of data. There are data on the natural history of the organism and the location & method of sampling.)  

[USGS Breeding Bird Survey](http://www.pwrc.usgs.gov/BBS/) (Breeding bird survey data back to 1966)  

[Bird Point Count Database](http://www.pwrc.usgs.gov/point/) (Depository of bird point-count data from across the US.)   

[Bird Studies Canada Nature Counts](http://www.bsc-eoc.org/birdmon/default/main.jsp) (Bird survey data archive for Canada, includes point counts and many other types of surveys.)  

[Avian Knowledge Network](http://www.avianknowledge.net/content/datasets)  (Archive of aggregated bird surveys from many organizations and studies across throughout the western hemisphere, including Latin America.)  

[NatureServe](http://www.natureserve.org/getData/index.jsp)  (Data on species of plants and animals in the Western Hemisphere, including detailed range maps)    

### RESEARCH PROJECT DATA ARCHIVES
[Dryad](http://datadryad.org/) (Data archives for bioscience data from peer-reviewed journal articles from a large consortium of journals)   

[Ecological Society of America (ESA) Data Registry](http://esapubs.org/archive/archive_D.htm)
Archive of ecological and environmental data from ESA publications)  

[National Center for Ecological Assessment & Synthesis (NCEAS) Data Repository](http://knb.ecoinformatics.org/knb/style/skins/nceas/index.jsp) (Data archive of contributed data sets of all types of ecological data.)  

[NCEAS Scientific Computing Database](http://www.nceas.ucsb.edu/scicomp/) (Clearinghouse of climatological, geospatial, and other data. Also has shareware software for analysis.)




## The Virtual Ecologist

#### QUESTION 1
Generate a dataset that violates one or more of the basic assumptions of standard linear regression. Make sure your dataset is biologically realistic! Justify in writing how biological processes could have produced the data, including (especially) the assumptions violation(s).

Some options: 
* use a non-normal error distribution
* introduce temporal autocorrelation
* introduce other types of correlation structure among the observations
* introduce a high-leverage outlier that comes from a different data-generating process

Use standard linear regression to analyze these data. 

Answer the following questions:

1. Is the estimate of the regression parameter *biased*?
2. How well does the confidence interval for the regression parameter match the true confidence interval? (this is a test for *precision*)
3. How well does the prediction interval match the true prediction interval?
4. Try some common data transformations to "correct" for any assumptions violations. For example, you might log transform 


#### QUESTION 2
Power analysis. 

### Simulating Data in R

General Strategy
The basic approach to simulating data|making \fake" data|is to (1) take the statistical model,
(2) pick some parameter values, and (3) use the random form of the model's probability distribution,
with the model embedded inside it, to generate random samples. So for a model yi  Zink( +
xi; 
), data can be simulated from the model using:
a <- 3
b <- 0.5
g <- 12
y <- rzink( n , a + b*x , g )
where a, b, and g are the parameters, x is a vector of (possibly fake) prediction values, and n is
equal to the length of x, the number of y values to generate.
Gaussian Example
Suppose we have a Gaussian regression model, yi  N( + 1xi + 2zi; ). You know the built-in
density function for Gaussian values is dnorm. The corresponding function to generate random
Gaussian values is rnorm|this is almost always the case, that the random function is named after
the density function, by changing the initial \d" to a \r". To simulate:
a <- 7.2
b1 <- 2.1
b2 <- -5
s <- 3
y <- rnorm( length(x) , mean=a + b1*x + b2*z , sd=s )
The vector y will hold randomly sampled Gaussian values.
