<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="NRES 746" />


<title>Model Selection</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NRES 746</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Schedule
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="schedule.html">Course Schedule</a>
    </li>
    <li>
      <a href="Syllabus.pdf">Syllabus</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="INTRO.html">Introduction to NRES 746</a>
    </li>
    <li>
      <a href="LECTURE1.html">Why simulate?</a>
    </li>
    <li>
      <a href="LECTURE2.html">Working with probabilities</a>
    </li>
    <li>
      <a href="LECTURE3.html">Data Generating Models</a>
    </li>
    <li>
      <a href="LECTURE4.html">Likelihood</a>
    </li>
    <li>
      <a href="LECTURE5.html">Optimization</a>
    </li>
    <li>
      <a href="LECTURE6.html">Bayesian #1: concepts</a>
    </li>
    <li>
      <a href="LECTURE7.html">Bayesian #2: mcmc</a>
    </li>
    <li>
      <a href="LECTURE8.html">Model Selection</a>
    </li>
    <li>
      <a href="LECTURE9.html">Performance Evaluation</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lab exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="LAB1.html">Lab 1: Algorithms in R</a>
    </li>
    <li>
      <a href="LAB2.html">Lab 2: Data generation</a>
    </li>
    <li>
      <a href="LAB3.html">Lab 3: Likelihood</a>
    </li>
    <li>
      <a href="LAB4.html">Lab 4: Bayesian inference</a>
    </li>
    <li>
      <a href="FINALPROJ.html">Final project overview</a>
    </li>
    <li>
      <a href="GIT_tutorial.html">Demo: version control in Git</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Student led topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="GLMM_Code_Demo_2025.html">GLMMs in R</a>
    </li>
    <li>
      <a href="centered and non-centeredyes.R">Non-centered GLMM in stan (R code)</a>
    </li>
    <li>
      <a href="Mixed_Effects_Demo.html">Mixture Models</a>
    </li>
    <li>
      <a href="MixtureDemo.R">Count models in stan (R code)</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Data sets
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="TreeData.csv">Tree Data</a>
    </li>
    <li>
      <a href="ReedfrogPred.csv">Reed Frog Predation Data</a>
    </li>
    <li>
      <a href="ReedfrogFuncresp.csv">Reed Frog Func Resp</a>
    </li>
  </ul>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Model Selection</h1>
<h4 class="author">NRES 746</h4>
<h4 class="date">Fall 2025</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#principle-of-parsimony-occams-razor"
id="toc-principle-of-parsimony-occams-razor">Principle of Parsimony
(“Occam’s razor”)</a></li>
<li><a href="#example-data-balsam-fir-data-from-ny"
id="toc-example-data-balsam-fir-data-from-ny">Example data: Balsam fir
data from NY</a></li>
<li><a href="#full-model" id="toc-full-model">FULL MODEL</a></li>
<li><a href="#reduced-models" id="toc-reduced-models">REDUCED MODELS</a>
<ul>
<li><a href="#likelihood-ratio-test-frequentist-solution"
id="toc-likelihood-ratio-test-frequentist-solution">Likelihood-ratio
test (frequentist solution)</a></li>
<li><a href="#information-theoretic-metrics"
id="toc-information-theoretic-metrics">Information-theoretic
metrics</a></li>
</ul></li>
<li><a href="#bayesian-model-selection"
id="toc-bayesian-model-selection">Bayesian Model Selection</a>
<ul>
<li><a href="#bayes-factor" id="toc-bayes-factor">Bayes Factor</a></li>
<li><a href="#bayesian-information-theoretic-criteria"
id="toc-bayesian-information-theoretic-criteria">Bayesian Information
Theoretic Criteria</a></li>
<li><a href="#explicit-bayesian-model-selection"
id="toc-explicit-bayesian-model-selection">Explicit Bayesian model
selection</a></li>
<li><a href="#model-averaging" id="toc-model-averaging">Model
averaging</a></li>
<li><a href="#regularization"
id="toc-regularization">Regularization</a></li>
<li><a href="#causal-inference" id="toc-causal-inference">Causal
Inference</a></li>
</ul></li>
</ul>
</div>

<p><a href="LECTURE8.R">Click here</a> for the companion R script for
this lecture.</p>
<p><strong>Model selection</strong> or <strong>model comparison</strong>
is a very common problem in science- that is, we often have multiple
competing hypotheses about how our data were generated and we want to
see which model is best supported by the available evidence.</p>
<p>If we can describe our data generating process explicitly as a set of
deterministic and stochastic components (i.e., likelihood functions),
then we can use likelihood-based methods (e.g., LRT, AIC, BIC, WAIC,
LOOIC, etc.) to infer which data generating model(s) could most
plausibly have generated our observed data.</p>
<div id="principle-of-parsimony-occams-razor" class="section level2">
<h2>Principle of Parsimony (“Occam’s razor”)</h2>
<p>We will discuss several alternative approaches to model selection in
ecology. However, all approaches follow the same basic principle- that –
all things equal, we should prefer the simpler model over any more
complex alternative. This is known as the ‘principle of parsimony’, or
‘Occam’s razor’.</p>
</div>
<div id="example-data-balsam-fir-data-from-ny" class="section level2">
<h2>Example data: Balsam fir data from NY</h2>
<p>Bolker uses a study of balsam fir in New York to illustrate model
selection. Perhaps it’s time to move on from Myxomatosis anyway…</p>
<p>Let’s load up the data first</p>
<pre class="r"><code># Load the balsam fir dataset
library(ggplot2)
library(emdbook)
data(FirDBHFec)
fir &lt;- na.omit(FirDBHFec[,c(&quot;TOTCONES&quot;,&quot;DBH&quot;,&quot;WAVE_NON&quot;)])
fir$TOTCONES &lt;- round(fir$TOTCONES)
head(fir)</code></pre>
<pre><code>##   TOTCONES  DBH WAVE_NON
## 1       19  9.4        n
## 2       42 10.6        n
## 3       40  7.7        n
## 4       68 10.6        n
## 5        5  8.7        n
## 6        0 10.1        n</code></pre>
<p>The goal of the original study was to test hypotheses about life
history evolution, but we will just use it to examine how fecundity
(total cones) varies as a function of tree size (DBH):</p>
<pre class="r"><code>plot(fir$TOTCONES ~ fir$DBH)   # fecundity as a function of tree size (diameter at breast height)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>One additional point of complexity in this data set- some trees were
sampled from areas undergoing a phenomenon called wave regeneration, in
which tree age follows a chronosequence as you move downwind (due to
larger trees at the wave front dying due to frost damage, allowing for
recruitment of new trees). Other trees were sampled from fir forests in
which there was no discernible wave regeneration pattern.</p>
<pre class="r"><code># tree fecundity by size, categorized into two site-level categories: &quot;wave&quot; and &quot;non-wave&quot; 

ggplot(fir,aes(DBH,TOTCONES)) + geom_point(aes(colour = WAVE_NON)) + theme_classic()</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Let’s assume (following Bolker) that fecundity increases as a
power-law relationship with DBH:</p>
<p><span class="math display">\[\mu = a\cdot DBH^{b}\]</span></p>
<p>Let’s also assume that fecundity follows a negative binomial
distribution with mean defined by the power law relationship above</p>
<p><span class="math display">\[Y = NegBin(\mu,k)\]</span></p>
<p>We can model each of these parameters (<em>a</em>, <em>b</em>, and
<em>k</em>) separately for trees from wave and non-wave populations.</p>
<p>We can also run simpler models in which some or all of these
parameters are modeled as the same for both populations.</p>
<p>Then we can try to address the question: <strong>which model is the
“best model”?</strong></p>
</div>
<div id="full-model" class="section level2">
<h2>FULL MODEL</h2>
<p>Here is a likelihood function for the <em>full model</em> – that is,
the most complex model (6-dimensional likelihood surface):</p>
<pre class="r"><code># build likelihood function for the full model: CONES ~ negBINOM( a(wave)*DBH^b(wave), dispersion(wave))
   
NLL_full &lt;- function(params){
  wave.code &lt;- as.numeric(fir$WAVE_NON)      # convert to ones and twos
  a &lt;- c(params[1],params[2])[wave.code]     # a parameters (two for wave and one for non-wave)
  b &lt;- c(params[3],params[4])[wave.code]      # b parameter (two for wave and one for non-wave)
  k &lt;- c(params[5],params[6])[wave.code]       # over-dispersion parameters (two for wave and one for non-wave)
  expcones &lt;- a*fir$DBH^b   # expected number of cones (deterministic component)
  -sum(dnbinom(fir$TOTCONES,mu=expcones,size=k,log=TRUE))     # add stochastic component: full data likelihood
}

params &lt;- c(a.n=1,a.w=1,b.n=1,b.w=1,k.n=1,k.w=1)

NLL_full(params)</code></pre>
<pre><code>## [1] 1762.756</code></pre>
<p>We can fit the full model using “optim” (using a gradient based
optimization routine), just like we have done before:</p>
<pre class="r"><code>## Find the MLE -----------------------

pars = c(a.n=1,a.w=1,b.n=1,b.w=1,k.n=1,k.w=1)
opt_full &lt;- optim(pars,NLL_full,method=&quot;BFGS&quot;)

MLE_full &lt;- opt_full$par
MinNLL_full &lt;- opt_full$value
MLE_full</code></pre>
<pre><code>##       a.n       a.w       b.n       b.w       k.n       k.w 
## 0.2886487 0.4093670 2.3536412 2.1473932 1.6542073 1.3247971</code></pre>
</div>
<div id="reduced-models" class="section level2">
<h2>REDUCED MODELS</h2>
<p>Let’s run a simpler model now. This time, let’s model the b parameter
as equal for wave and nonwave populations:</p>
<pre class="r"><code># build likelihood function for a reduced model: CONES ~ negBINOM( a(wave)*DBH^b, dispersion(wave))

NLL_constb &lt;- function(params){
  wave.code &lt;- as.numeric(fir$WAVE_NON)      # convert to ones and twos
  a &lt;- c(params[1],params[2])[wave.code]      # a parameters
  b &lt;- params[3]                              # b parameter (not a function of wave/nonwave)
  k &lt;- c(params[4],params[5])[wave.code]      # dispersion parameters
  expcones &lt;- a*fir$DBH^b
  -sum(dnbinom(fir$TOTCONES,mu=expcones,size=k,log=TRUE))
}

params &lt;- c(a.n=1,a.w=1,b=1,k.n=1,k.w=1)

NLL_constb(params)</code></pre>
<pre><code>## [1] 1762.756</code></pre>
<p>And we can fit the full model using “optim”:</p>
<pre class="r"><code>### Find the MLE

opt_constb &lt;- optim(fn=NLL_constb,par=c(a.n=1,a.w=1,b=1,k.n=1,k.w=1),method=&quot;BFGS&quot;)

MLE_constb = opt_constb$par

MinNLL_constb = opt_constb$value
MLE_constb</code></pre>
<pre><code>##       a.n       a.w         b       k.n       k.w 
## 0.3477735 0.3218252 2.2698370 1.6530597 1.3231697</code></pre>
<p>Let’s compute <em>-2 times the log likelihood</em> (<span
class="math inline">\(-2*log(likelihood)\)</span>) of the two models at
the MLE – That is, we compute <span
class="math inline">\(-2*log(Lik@MLE)\)</span> for each alternative
model.</p>
<pre class="r"><code># compute -2*loglik for each model at the MLE

ms_full &lt;- 2*MinNLL_full     # this is 2 * min.nll = -2*logLik_at_MLE
ms_constb &lt;- 2*MinNLL_constb

ms_full</code></pre>
<pre><code>## [1] 2270.02</code></pre>
<pre class="r"><code>ms_constb</code></pre>
<pre><code>## [1] 2270.267</code></pre>
<p>Note here that the log-likelihood of the full model is lower
(“better”: that is, the data are more likely to be produced under this
model) than the the reduced model. <em>This should always be the
case</em>- if not, something is wrong. That is, the plausibility of
producing the observed data under a model fitted to those data should
<em>always</em> increase when more parameters are added!</p>
<p>This is where the principle of parsimony comes into play! Somehow we
need a method that penalizes the complexity of the model, so that we can
at least sometimes let the simpler model ‘win’ if it is indeed better
supported by the evidence!</p>
<p>One way is to use our old friend, the Likelihood Ratio Test
(LRT)!</p>
<div id="likelihood-ratio-test-frequentist-solution"
class="section level3">
<h3>Likelihood-ratio test (frequentist solution)</h3>
<p>We have encountered the LRT once before, in the context of generating
confidence intervals from likelihood surfaces (in the neighborhood of
the MLE). The same principle applies for model selection. The LRT
assesses whether the extra goodness-of-fit of the full model is worth
the complexity of the additional parameters.</p>
<p>As you recall, the likelihood ratio is defined (obviously) as the
ratio of two likelihoods. The numerator represents the likelihood of a
reduced model (fewer free parameters) that is nested within a full model
– which in turn serves as the denominator:</p>
<p><span
class="math display">\[\frac{Likelihood_{reduced}}{Likelihood_{full}}\]</span></p>
<p>The raw likelihood ratio under the null hypothesis does not have a
known distribution. BUT, if we first convert the likelihood ratio to
<strong>-2X the difference in log likelihoods</strong>, we have a
statistic that approximately follows a Chi-squared distribution.</p>
<p><span
class="math display">\[-2ln(\frac{Likelihood_{reduced}}{Likelihood_{full}})\]</span></p>
<p>Which can also be written as:</p>
<p><span class="math display">\[-2ln(Likelihood_{reduced}) -
-2ln(Likelihood_{full})\]</span></p>
<p>Which can also be written as:</p>
<p><span class="math display">\[2[ln(Likelihood_{full} -
ln(Likelihood_{reduced})]\]</span> that is: 2 times the absolute
difference in log likelihood between the full and reduced models. [note
that the order of the likelihoods is often reversed because we tend to
deal with negative log likelihoods instead of log likelihoods]</p>
<p>When expressed this way, this likelihood ratio statistic (assuming
the simpler model is the true model) is asymptotically Chi-squared
distributed with df equal to the number of fixed dimensions (difference
in free parameters between the full and reduced model). This way, we
only reject the simpler model if there is sufficient evidence- that is,
when the deviance is much larger than expected under the null model.</p>
<p>The LRT can be used for <em>two-way model comparison</em> as long as
one model is nested within the other (full model vs. reduced model). If
the models are not nested then the LRT doesn’t really make sense or have
theoretical support.</p>
<pre class="r"><code># Likelihood-Ratio test -----------------------

Deviance &lt;- ms_constb - ms_full 
Deviance    # very small deviance</code></pre>
<pre><code>## [1] 0.2467505</code></pre>
<pre class="r"><code>Chisq.crit &lt;- qchisq(0.95,1)
Chisq.crit</code></pre>
<pre><code>## [1] 3.841459</code></pre>
<pre class="r"><code>Deviance &gt;= Chisq.crit   # perform the LRT- don&#39;t reject the simpler model</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>1-pchisq(Deviance,1)   # p-value</code></pre>
<pre><code>## [1] 0.6193725</code></pre>
<pre class="r"><code># Visualize the likelihood ratio test- compare the observed deviance with the distribution of deviances expected under the null hypothesis

curve(dchisq(x,df=1),0,5)
abline(v=Deviance,col=&quot;red&quot;,lwd=4)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Clearly, the gain in model performance is not worth the extra
complexity in this case (the observed deviance could easily be produced
by random chance!). Therefore, we favor the reduced model.</p>
<p>What about if we try a different reduced model? This time, we decide
to fix the a, b, and k parameters, so the “wave” factor is not
considered.</p>
<pre class="r"><code># Try a different reduced model: CONES ~ negBINOM( a*DBH^b, dispersion)

NLL_nowave &lt;- function(params){
  a &lt;- params[1]      # a parameters
  b &lt;- params[2]      # b parameter (not a function of wave/nonwave)
  k &lt;- params[3]      # dispersion parameters
  expcones &lt;- a*fir$DBH^b
  -sum(dnbinom(fir$TOTCONES,mu=expcones,size=k,log=TRUE))
}

params &lt;- c(a=1,b=1,k=1)

NLL_nowave(params)</code></pre>
<pre><code>## [1] 1762.756</code></pre>
<p>And we use “optim” to locate the maximum likelihood estimate:</p>
<pre class="r"><code># Find the MLE

opt_nowave &lt;- optim(fn=NLL_nowave,par=params,method=&quot;L-BFGS-B&quot;)

MLE_nowave = opt_nowave$par

MinNLL_nowave = opt_nowave$value

MLE_nowave</code></pre>
<pre><code>##         a         b         k 
## 0.3036727 2.3197228 1.5029500</code></pre>
<p>Now we can perform a LRT to see which model is better!</p>
<pre class="r"><code># Perform LRT -- this time with three fewer free parameters in the reduced model

ms_full &lt;- 2*MinNLL_full

ms_nowave &lt;- 2*MinNLL_nowave

Deviance &lt;- ms_nowave - ms_full 
Deviance</code></pre>
<pre><code>## [1] 2.009944</code></pre>
<pre class="r"><code>Chisq.crit &lt;- qchisq(0.95,df=3)   # now three additional params in the more complex model!
Chisq.crit</code></pre>
<pre><code>## [1] 7.814728</code></pre>
<pre class="r"><code>Deviance&gt;=Chisq.crit</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>1-pchisq(Deviance,df=3)   # p-value</code></pre>
<pre><code>## [1] 0.5703454</code></pre>
<pre class="r"><code># Visualize the likelihood ratio test (test statistic and sampling distribution under the null)
curve(dchisq(x,df=3),0,15)
abline(v=Deviance,col=&quot;red&quot;,lwd=4)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Again, the difference in deviance does not justify the additional
parameters. This difference in deviance between the full and restricted
model could easily be produced easily by random sampling variation.</p>
<p>Remember <em>this is a frequentist test</em>. The null hypothesis is
that there is no difference between the restricted model and the more
complex model. So we are imagining multiple alternative universes where
we are collecting thousands of datasets under the null hypothesis
(simpler model is correct– that is, the extra parameters are junk) and
determining a maximum likelihood estimate for the full model (with
meaningless free params) and a reduced model where we <em>fix</em> the
value of one or more of our junk free parameters at the
<strong>true</strong> parameter value of zero. Even though the data
generating process is the same each time, each dataset we collect will
yield a slightly different MLE for the full model and the reduced model.
The deviance (-2*log likelihood ratio) between the restricted model and
the full model (under the null hypothesis) is asymptotically Chi-squared
distributed with df = number of dimensions that were “fixed”!</p>
<p>As you can imagine, there are a lot of pairwise comparisons that
could be generated, even in this simple example. For instance, there are
15 pairwise comparisons that could be produced from even this simple
example. What about more complex models? Clearly this can get a bit
unwieldy!</p>
<p>In addition, not all models we wish to compare will necessarily be
nested. For example, consider the model selection exercise we were
performing in lab- comparing the M-M fit to the Ricker fit. Since these
models aren’t nested, there is not clearly a “reduced” and a “full”
model and we can’t perform a LRT.</p>
</div>
<div id="information-theoretic-metrics" class="section level3">
<h3>Information-theoretic metrics</h3>
<p>Information-theoretic metrics for model comparison, like the well
known Akaike’s Information Criterion (AIC), provide a way to get around
the issues with LRT. These metrics allow us to make tables for comparing
multiple models simultaneously.</p>
<p>Metrics like AIC represent (theoretically) the relative divergence
between your fitted model and the “true” data generating model, even if
the ‘true’ model is unknown. Information-theoretic metrics are composed
of a negative-log-likelihood component (e.g., <span
class="math inline">\(-2\ell\)</span>, in which <span
class="math inline">\(\ell\)</span> is the log likelihood of the fitted
model and lower values mean better fit) and a <em>parsimony penalty
term</em> (for which lower values mean more parsimony). For AIC, the
penalty term is twice the number of parameters (<span
class="math inline">\(2k\)</span>). The models with the lowest values of
the information criterion are considered the best model (marrying good
fit and parsimony)</p>
<div id="akaikes-information-criterion-aic" class="section level4">
<h4>Akaike’s Information Criterion (AIC)</h4>
<p>NOTE: AIC is still widely used (and misused) so it is important to
understand!</p>
<p>AIC is computed using the following very simple equation:</p>
<p><span class="math display">\[AIC = -2 \ell_{max} + 2k\]</span></p>
<p><span class="math inline">\(\ell_{max}\)</span> is the maximum of the
log-likelihood surface.</p>
<p><span class="math inline">\(k\)</span> is the number of free
parameters in the model</p>
<p>As with all information-theoretic metrics, we look for the model
associated with the minimum value (lowest value corresponds with best
model fit). This is the “best model”, at least among the set of models
tested.</p>
<p>For small sample sizes, Burnham and Anderson (2002) recommend that a
finite-size correction should be used:</p>
<p><span class="math inline">\(AIC_c = AIC +
\frac{2k(k+1)}{n-k-1}\)</span></p>
<p>A common <em>rule of thumb</em> is that models within 2 AIC units (or
AICc units) of the best model are “reasonable” (does this “rule of 2”
sound familiar?)</p>
</div>
<div id="schwarz-information-criterion-bic" class="section level4">
<h4>Schwarz information criterion (BIC)</h4>
<p>Another common I-T metric is the Schwarz, or <em>Bayesian</em>
information criterion. The penalty term for BIC is (log n)*k.</p>
<p><span class="math inline">\(BIC = -2\ell_{max} + (log(n))\cdot
k\)</span></p>
<p>In general, BIC is more conservative than AIC- that is, more likely
to select the simpler model (since the penalty term is generally
greater).</p>
<p>Although the Schwarz criterion has a Bayesian justification (as does
AIC), it is computed from a point estimate (using the log-likelihood at
the MLE) and so it doesn’t pass any real test for being Bayesian –
Bayesian analyses don’t treat parameters as points, but as full
probability distributions.</p>
</div>
<div id="aic-in-action" class="section level4">
<h4>AIC in action</h4>
<p>Let’s return to the fir fecundity model, and use AIC to select among
a set of models. Let’s first fit a couple more candidate models…</p>
<p>This time, we decide to fix the <em>a</em>, and <em>k</em>
parameters, so the “wave” factor is only considered for the <em>b</em>
parameter.</p>
<pre class="r"><code># Information-theoretic metrics for model-selection ------------------------------

# Akaike&#39;s Information Criterion (AIC)

## First, let&#39;s build another likelihood function: whereby only the &quot;b&quot; parameter differs by &quot;wave&quot; sites

NLL_constak &lt;- function(params){
  wave.code &lt;- as.numeric(fir$WAVE_NON)      # convert to ones and twos
  a &lt;- params[1]                             # a parameters
  b &lt;- c(params[2],params[3])[wave.code]                              # b parameter (not a function of wave/nonwave)
  k &lt;- params[4]                               # dispersion parameters
  expcones &lt;- a*fir$DBH^b
  -sum(dnbinom(fir$TOTCONES,mu=expcones,size=k,log=TRUE))
}

params &lt;- c(a=1,b.n=1,b.w=1,k=1)  

NLL_constak(params)</code></pre>
<pre><code>## [1] 1762.756</code></pre>
<p>And we can fit the full model using “optim”:</p>
<pre class="r"><code>### Fit the new model

opt_constak &lt;- optim(fn=NLL_constak,par=params)

MLE_constak= opt_constak$par

MinNLL_constak = opt_constak$value

ms_constak &lt;- 2*MinNLL_constak
MLE_constak</code></pre>
<pre><code>##         a       b.n       b.w         k 
## 0.3448975 2.2745907 2.2327297 1.5057655</code></pre>
<p>Finally, let’s fit a model with no “wave” effect, but where we assume
the error is Poisson distributed…</p>
<pre class="r"><code>### Now, let&#39;s build and fit one more final model- this time with no wave effect and a Poisson error distribution

PoisLik_nowave &lt;- function(params){
  a &lt;- params[1]      # a parameters
  b &lt;- params[2]      # b parameter (not a function of wave/nonwave)
  expcones &lt;- a*fir$DBH^b
  -sum(dpois(fir$TOTCONES,lambda=expcones,log=TRUE))
}

params &lt;- c(a=1,b=1)

PoisLik_nowave(params)</code></pre>
<pre><code>## [1] 15972.6</code></pre>
<pre class="r"><code>opt_pois &lt;- optim(fn=PoisLik_nowave,par=params)

MLE_pois= opt_pois$par

MinNLL_pois= opt_pois$value

ms_pois &lt;- 2*MinNLL_pois

MLE_pois</code></pre>
<pre><code>##         a         b 
## 0.2613297 2.3883860</code></pre>
<p><strong>Note</strong> we could not compare the Poisson model to the
Negative Binomial model using LRT- one is not nested within the
other!</p>
<p>Now we can compare the five models we have run so far using AIC</p>
<pre class="r"><code># Compare all five models using AIC!

AIC_constak &lt;- ms_constak + 2*4
AIC_full &lt;- ms_full + 2*6
AIC_constb &lt;- ms_constb + 2*5
AIC_nowave &lt;- ms_nowave + 2*3
AIC_pois &lt;- ms_pois + 2*2

AICtable &lt;- data.frame(
  Model = c(&quot;Full&quot;,&quot;Constant b&quot;,&quot;Constant a and k&quot;,&quot;All constant&quot;,&quot;Poisson&quot;),
  AIC = c(AIC_full,AIC_constb,AIC_constak,AIC_nowave,AIC_pois),
  LogLik = c(ms_full/-2,ms_constb/-2,ms_constak/-2,ms_nowave/-2,ms_pois/-2),
  params = c(6,5,4,3,2),
  stringsAsFactors = F
)

AICtable$DeltaAIC &lt;- AICtable$AIC-AICtable$AIC[which.min(AICtable$AIC)]

AICtable$Weights &lt;- round(exp(-0.5*AICtable$DeltaAIC) / sum(exp(-0.5*AICtable$DeltaAIC)),3)

AICtable$AICc &lt;- AICtable$AIC + ((2*AICtable$params)*(AICtable$params+1))/(nrow(fir)-AICtable$params-1)

AICtable[order(AICtable$AIC),c(1,7,2,5,6,4,3)]</code></pre>
<pre><code>##              Model     AICc      AIC    DeltaAIC Weights params    LogLik
## 4     All constant 2278.131 2278.030    0.000000   0.516      3 -1136.015
## 3 Constant a and k 2279.684 2279.515    1.484647   0.246      4 -1135.758
## 2       Constant b 2280.521 2280.267    2.236807   0.169      5 -1135.134
## 1             Full 2282.378 2282.020    3.990054   0.070      6 -1135.010
## 5          Poisson 6327.714 6327.664 4049.633378   0.000      2 -3161.832</code></pre>
<p>This AIC table shows us that the simplest model is best! Despite the
fact that the deviance is lowest for the full model (principle of
parsimony at work)</p>
</div>
</div>
</div>
<div id="bayesian-model-selection" class="section level2">
<h2>Bayesian Model Selection</h2>
<p>Can we do model selection in a Bayesian framework? The answer is yes!
One elegant metric that is used by Bayesians for model selection is the
<em>Bayes Factor</em> (below). The Bayes factor is defined as the ratio
of <em>marginal likelihoods</em> of two models. That is- we should
prefer the model that is more likely to produce the data, all else being
equal.</p>
<p>In addition, there are some I-T metrics for Bayesian analyses that
make model selection pretty much as easy as building an AIC table!</p>
<div id="bayes-factor" class="section level3">
<h3>Bayes Factor</h3>
<p>Recall that our I-T metrics, as well as likelihood ratio tests, used
the value of the likelihood surface at the MLE. That is, we are only
taking into account a single point on the likelihood surface to
represent what our data have to say about our model.</p>
<p>Bayesians compute a posterior distribution that takes into account
the entire likelihood surface (and the prior distribution)– that is, we
now are working with an entire posterior distribution rather than just a
single point.</p>
<p>The <em>marginal likelihood</em> represents the likelihood averaged
across parameter space (where the prior serves to weight this average to
emphasize the parts of the parameter space with higher a priori degrees
of belief.</p>
<p><span class="math display">\[\overline{\mathcal{L}} = \int
P(data|\theta) P(\theta) d \theta\]</span></p>
<p>The marginal likelihood represents the <em>average fit of a given
model structure to the data</em>.</p>
<p>This should look familiar! It is the denominator of the Bayes rule
formula – also known as the probability of the data, or the
<strong>model evidence</strong>.</p>
<p>The higher the marginal likelihood, the more likely that model
structure is to produce the data.</p>
<p>The ratio of marginal likelihoods is known as the <strong>Bayes
factor</strong> and is an elegant method for comparing models in a
Bayesian context.</p>
<p><span class="math display">\[\overline{\mathcal{L}}_1 /
\overline{\mathcal{L}}_2\]</span></p>
<p>This is interpreted as the odds in favor of model 1 versus model
2.</p>
<p>This simple formula penalizes complexity for free. Simpler models
will generally have higher marginal likelihoods than more complex models
after all of parameter space is taken into account. This is because
higher dimensional spaces have more “bad” areas of parameter space and
less “good” areas. So while the maximum of the likelihood surface will
always be higher in a more complex model, the average of the likelihood
surface can be lower for the more complex model (which has additional
dimension(s) to average across).</p>
<p>Bayes Factors ‘feel’ like likelihood ratios, but they really are
fundamentally different. That is, except in the case where there is no
parameter uncertainty, like the medical testing example from earlier in
the course (in which case the likelihood ratio and the bayes factor are
identical).</p>
<p>In practice, computing marginal likelihoods can be tricky because,
well, multi-dimensional integration! Recall that we use MCMC partially
to avoid computing the denominator in the Bayes Rule formula. Bayes
factors, in contrast, are computed entirely from the denominators of
Bayesian parameter estimation problems!</p>
<p>Furthermore, the prior specification can have a huge impact on Bayes
factors, which can be unsettling at best and highly misleading at
worst!</p>
<div id="bayes-factor-example" class="section level4">
<h4>Bayes Factor Example</h4>
<p>A simple binomial example can illustrate Bayes factors quite
nicely.</p>
<p>Imagine we conduct a tadpole experiment where we are interested in
estimating the mortality rate <em>p</em> due to a pesticide, on the
basis of the number of dead tadpoles observed out of 10 in a treated
tank. We are interested in comparing a simple model where <em>p</em> is
fixed at 0.5 (a ‘point null’ model) with a more complex model where
<em>p</em> is a <em>free parameter</em> estimated from data. That is, we
are testing the hypothesis that <em>p</em> is different from 50%.</p>
<p>First let’s take a look at the simple model.</p>
<pre class="r"><code># Bayes factor example  ---------------------

# take a basic binomial distribution with parameter p fixed at 0.5:

probs1 &lt;- dbinom(0:10,10,0.5)          
names(probs1) = 0:10
barplot(probs1,ylab=&quot;probability&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>## Q: What is the *marginal likelihood* under this simple model for an observation of 2 mortalities out of 10? 

## A:

dbinom(2,10,0.5)  # note: there is no parameter uncertainty here, so nothing to integrate or sum across</code></pre>
<pre><code>## [1] 0.04394531</code></pre>
<p><strong>Q</strong> What is the <em>marginal likelihood</em> under
this simple model for an observation of 2 mortalities out of 10? How
about 3 mortalities?</p>
<p><strong>A</strong> It is exactly 0.0439453. That is, there is no
marginalizing to do since there is no free parameter to marginalize
over.</p>
<p>Now let’s consider a more ‘complex’ model, where <em>p</em> is a free
parameter (one additional free parameter relative to the simple model).
First, let’s assume that the parameter <em>p</em> is assigned a uniform
<span class="math inline">\(beta(1,1)\)</span> prior across parameter
space:</p>
<pre class="r"><code>## Now we can consider a model whereby &quot;p&quot; is a free parameter
curve(dbeta(x,1,1))  # uniform prior on &quot;p&quot;</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>What is the marginal likelihood of observing 2 mortalities under this
model?</p>
<p>In other words, what is the average probability of observing 2
mortalities, averaged across all possible values of <em>p</em>???</p>
<p>Intuitively, because all values of <em>p</em> are equally likely, all
possible observations (0 mortalities, 2 mortalities, N mortalities)
should be equally likely! That is, neither the likelihood function nor
the prior distribution favors any particular observation (0 to 10) over
any other.</p>
<p>We can do this mathematically…</p>
<p>For two observed mortalities, the marginal likelihood is:</p>
<pre class="r"><code># Compute the marginal likelihood of observing 2 mortalities

# ?integrate
binom2 &lt;- function(x) dbinom(x=2,size=10,prob=x)
marginal_likelihood &lt;- integrate(f=binom2,0,1)$value    # use &quot;integrate&quot; function in R
marginal_likelihood  # equal to 0.0909 = 1/11</code></pre>
<pre><code>## [1] 0.09090909</code></pre>
<p>For three observed mortalities, the marginal likelihood (probability
of observing a “3” across all possible values of p) is:</p>
<pre class="r"><code># Compute the marginal likelihood of observing 3 mortalities

binom3 &lt;- function(x) dbinom(x=3,size=10,prob=x)
marginal_likelihood &lt;- integrate(f=binom3,0,1)$value    # use &quot;integrate&quot; function
marginal_likelihood   # equal to 0.0909 = 1/11</code></pre>
<pre><code>## [1] 0.09090909</code></pre>
<p>Basically, if p could be anything between 0 and 1, no particular
observation is favored over any other prior to observing any real
data:</p>
<pre class="r"><code># simulate data from the model across all possible values of the parameter &quot;p&quot;

lots=1000000
a_priori_data &lt;- rbinom(lots,10,prob=rbeta(lots,1,1))   # no particular observation is favored
for_hist &lt;- table(a_priori_data)/lots
barplot(for_hist,xlab=&quot;Potential Observation&quot;,ylab=&quot;Marginal likelihood&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Therefore, since there are 11 possible observations (outcomes of the
binomial distribution of size=10), the marginal likelihood of any
particular data observation under the model with p as a free parameter
should be 1/11 = 0.0909091.</p>
<p>Here is a visualization of the marginal likelihood across all
possible data observations:</p>
<pre class="r"><code># Visualize the marginal likelihood of all possible observations

probs2 &lt;- rep(1/11,times=11)          
names(probs2) = 0:10
barplot(probs2,ylab=&quot;probability&quot;,ylim=c(0,1))</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Now let’s overlay the marginal likelihoods for the simpler model
(which really isn’t ‘marginalized’ across anything since there are zero
free parameters):</p>
<pre class="r"><code># Overlay the marginal likelihood of the simpler model, with p fixed at 0.5

probs2 &lt;- rep(1/11,times=11)          
names(probs2) = 0:10
barplot(probs2,ylab=&quot;probability&quot;,ylim=c(0,1))

probs1 &lt;- dbinom(0:10,10,0.5)          
names(probs1) = 0:10
barplot(probs1,ylab=&quot;probability&quot;,add=T,col=&quot;red&quot;,density=20)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Assuming we observed 2 mortalities, what is the Bayes Factor? Which
model is better?</p>
<pre class="r"><code># Finally, compute the bayes factor given that we observed 2 mortalities. Which model is better?

probs2 &lt;- rep(1/11,times=11)          
names(probs2) = 0:10
barplot(probs2,ylab=&quot;probability&quot;,ylim=c(0,1))

probs1 &lt;- dbinom(0:10,10,0.5)          
names(probs1) = 0:10
barplot(probs1,ylab=&quot;probability&quot;,add=T,col=&quot;red&quot;,density=20)

abline(v=3,col=&quot;green&quot;,lwd=4 )</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre class="r"><code>BayesFactor = (1/11)/dbinom(2,10,0.5)   
BayesFactor</code></pre>
<pre><code>## [1] 2.068687</code></pre>
<p>Here, the Bayes factor of around 2 indicates that the data lend
support to the more complex model!</p>
<p>What if the data instead were 3 mortalities? Which model is the best
model?</p>
<pre class="r"><code># Compute the bayes factor given that we observed 3 mortalities. Which model is better now?

probs2 &lt;- rep(1/11,times=11)          
names(probs2) = 0:10
barplot(probs2,ylab=&quot;probability&quot;,ylim=c(0,1))

probs1 &lt;- dbinom(0:10,10,0.5)          
names(probs1) = 0:10
barplot(probs1,ylab=&quot;probability&quot;,add=T,col=&quot;red&quot;,density=20)

abline(v=4.3,col=&quot;green&quot;,lwd=4 )</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<pre class="r"><code>BayesFactor = dbinom(3,10,0.5)/(1/11)
BayesFactor</code></pre>
<pre><code>## [1] 1.289063</code></pre>
<p>This time, <em>The simpler model wins</em>!!! That would never happen
if we compared maximum likelihood estimates- the likelihood of the
(fitted) more complex model will always be (equal or) lower (i.e., the
likelihood of three successes at p=0.3 is higher than the likelihood of
three successes at p=0.5)! That’s why we have to penalize or
<em>regularize</em> more complex models to put them on a level playing
field with the simpler models.</p>
<p>We can visualize this! First of all, what is the maximum likelihood
estimate for p under the model with 3 mortality observations?</p>
<pre class="r"><code># Visualize the likelihood ratio

# probs2 &lt;- rep(1/11,times=11)          
# names(probs2) = 0:10
# barplot(probs2,ylab=&quot;probability&quot;,ylim=c(0,1))

probs1 &lt;- dbinom(0:10,10,0.5)          
names(probs1) = 0:10
barplot(probs1,ylab=&quot;probability&quot;,col=&quot;red&quot;,density=20,ylim=c(0,1))

probs3 &lt;- dbinom(0:10,10,0.3)          
names(probs3) = 0:10
barplot(probs3,ylab=&quot;probability&quot;,add=T,col=&quot;green&quot;,density=10,angle = -25)

abline(v=4.3,col=&quot;green&quot;,lwd=4 )</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>So clearly the raw likelihood ratio favors the more complex model
(fitted parameter “p”) vs the simple, 0-parameter model!</p>
<p>What does the likelihood-ratio test have to say though?</p>
<pre class="r"><code># LRT: simple model (p fixed at 0.5) vs complex model (p is free parameter)

Likelihood_simple &lt;- dbinom(3,10,0.5)
Likelihood_complex &lt;- dbinom(3,10,0.3)
Likelihood_simple</code></pre>
<pre><code>## [1] 0.1171875</code></pre>
<pre class="r"><code>Likelihood_complex</code></pre>
<pre><code>## [1] 0.2668279</code></pre>
<pre class="r"><code>-2*log(Likelihood_simple)--2*log(Likelihood_complex)</code></pre>
<pre><code>## [1] 1.645658</code></pre>
<pre class="r"><code>qchisq(0.95,1)</code></pre>
<pre><code>## [1] 3.841459</code></pre>
<pre class="r"><code>pchisq(1.64,1)    # very high p value, simpler model is preferred</code></pre>
<pre><code>## [1] 0.7996745</code></pre>
<p>What about AIC?</p>
<pre class="r"><code># AIC: simple model (p fixed at 0.5) vs complex model (p is free parameter)

AIC_simple &lt;- -2*log(Likelihood_simple) + 2*0
AIC_complex &lt;-  -2*log(Likelihood_complex) + 2*1

AIC_simple</code></pre>
<pre><code>## [1] 4.28796</code></pre>
<pre class="r"><code>AIC_complex    </code></pre>
<pre><code>## [1] 4.642303</code></pre>
<p>What about AICc?</p>
<p><span class="math inline">\(AIC_c = AIC +
\frac{2k(k+1)}{n-k-1}\)</span></p>
<pre class="r"><code>### Alternatively, use AICc

AICc_simple &lt;- -2*log(Likelihood_simple) + 0 + 0
AICc_complex &lt;-  -2*log(Likelihood_complex) + 1 + ((2*2)/(3-1-1))

AICc_simple</code></pre>
<pre><code>## [1] 4.28796</code></pre>
<pre class="r"><code>AICc_complex    </code></pre>
<pre><code>## [1] 7.642303</code></pre>
<p>What about BIC?</p>
<pre class="r"><code># Alternatively, try BIC

BIC_simple &lt;- -2*log(Likelihood_simple) + log(10)*0
BIC_complex &lt;-  -2*log(Likelihood_complex) + log(10)*1

BIC_simple</code></pre>
<pre><code>## [1] 4.28796</code></pre>
<pre class="r"><code>BIC_complex    </code></pre>
<pre><code>## [1] 4.944888</code></pre>
<p>All these methods give the same basic answer- that the simple model
is better, even though the complex model fits better!</p>
</div>
</div>
<div id="bayesian-information-theoretic-criteria"
class="section level3">
<h3>Bayesian Information Theoretic Criteria</h3>
<p>The first widely used, fully Bayesian I-T criterion was called
Deviance Information Criterion, or DIC (which was the butt of many
statistician jokes back in the day).</p>
<p>Deviance Information Criterion is computed by default in JAGS and
WinBUGS. It is analogous to other I-T metrics like AIC (and therefore
easy to interpret and use)!</p>
<p>However, DIC has been largely superseded by other I-T criterion for
MCMC-fitted Bayesian models: these are WAIC and LOOIC. We will compute
these using stan.</p>
<p>The WAIC criterion (also known as the Wattanabe-Akaike information
criterion, or the ‘widely applicable information criterion’) metric is
also interpretable just like AIC, BIC and DIC and allows us to compare
models fitted in a Bayesian framework via MCMC:</p>
<p><span class="math display">\[WAIC = -2(lppd - P_{WAIC})\]</span>,</p>
<p><span class="math display">\[lppd = \sum_i log \int_\theta
P(y_i|\theta)P(\theta | y)d\theta\]</span>,</p>
<p>where the integral is approximated by averaging across the posterior
distribution of the likelihood of each data point. Therefore we need to
monitor or compute the likelihood of each data point in our MCMC model
fitting algorithm.</p>
<p><span class="math display">\[P_{WAIC} = \sum_i
Var[log(P(y_i|\theta_{post})]\]</span></p>
<p>P_WAIC is a penalty term, and is often referred to as the effective
number of parameters. Less complex models are more constrained (less
flexible) and that will correspond with less variability in the
likelihood of each data point across MCMC samples. More complex models
are more flexible/variable and therefore will have a greater
penalty.</p>
<p>Finally, the WAIC metric has largely been superseded by the ‘loo’
methods, including LOO-CV and LOOIC. LOOIC is often indistinguishable
from WAIC:</p>
<p><span class="math display">\[LOOIC = -2\sum_i log \int_\theta
P(y_i|\theta)P(\theta_{-y_i})d\theta\]</span> Notice that in its pure
form you need to re-compute the model N times, each time leaving out one
data point. This is impractical. So, in practice, we use a technique
called Pareto-smoothed importance sampling (PSIS). In PSIS, we use
creative weighted averaging to approximate the cross validation. More
surprising (less likely) observations are assigned more weight than less
surprising observations.</p>
<p>One advantage of these methods is that they provide additional model
fit diagnostics based on (PSIS), like the Pareto K statistic. If the
pareto-k statistic is less than 0.7, the PSIS method should provide a
good approximation of the LOO score. If pareto-k is greater than 0.7,
then the PSIS approximation may be unreliable due to highly influential
observations in your dataset.</p>
<p>When used to compute the approximate leave-one-out cross validation
metric, this technique is known as PSIS-LOO.</p>
<p>First, let’s write a ‘stan’ model for the fir data:</p>
<pre><code>

data {
  int&lt;lower = 1&gt; N;
  array [N] int&lt;lower=0&gt; obs_cones;
  vector&lt;lower=0&gt; [N] DBH;
  array [N] int&lt;lower=1,upper=2&gt; wave_ndx; 
}

parameters {
  vector[2] loga, b, logbeta;
}

transformed parameters {
  vector[2] a = exp(loga);
  vector[2] beta = exp(logbeta);
}

model  {
  vector[N] mean_cones = a[wave_ndx] .* DBH .^ b[wave_ndx];   // power function: a*DBH^b
  vector[N] alpha = mean_cones .* beta[wave_ndx];
  obs_cones ~ neg_binomial(alpha,beta[wave_ndx]);
}

generated quantities {   // need log_lik of each data point for model selection
  vector[N] log_lik; // N is the number of data points
  {
    real m2, a2;
    for (n in 1:N) {
       m2 = a[wave_ndx[n]] * DBH[n]^b[wave_ndx[n]];   // power function: a*DBH^b
       a2 = m2 * beta[wave_ndx[n]];
       log_lik[n] = neg_binomial_lpmf(obs_cones[n] | a2, beta[wave_ndx[n]]);
    }
  }
}
</code></pre>
<p>Then we need to package the data for stan</p>
<pre class="r"><code># Package the data for stan

stan_data &lt;- list(
  N = nrow(fir),
  obs_cones = fir$TOTCONES,
  wave_ndx = as.numeric(fir$WAVE_NON),
  DBH = fir$DBH
)
#data.package</code></pre>
<p>Then we can run the model!</p>
<pre class="r"><code># Run the model in stan

library(cmdstanr)    # load packages
library(bayesplot)
library(posterior)
options(mc.cores = 4) 

# compile the model using:
firmodel_full &lt;- cmdstan_model(&quot;firmodel_full.stan&quot;) # Compile stan model

fit_full &lt;- suppressMessages( firmodel_full$sample(
  data = stan_data,
  chains = 4,
  iter_warmup = 500,
  iter_sampling = 500,
  refresh = 0
)  )</code></pre>
<pre><code>## Running MCMC with 4 parallel chains...
## 
## Chain 3 finished in 2.8 seconds.
## Chain 1 finished in 2.9 seconds.
## Chain 4 finished in 2.9 seconds.
## Chain 2 finished in 3.2 seconds.
## 
## All 4 chains finished successfully.
## Mean chain execution time: 3.0 seconds.
## Total execution time: 3.4 seconds.</code></pre>
<pre class="r"><code># fit_full$summary()
samples &lt;- fit_full$draws(format=&quot;draws_df&quot;)
bayesplot::mcmc_trace(samples,&quot;a[1]&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<pre class="r"><code>bayesplot::mcmc_trace(samples,&quot;b[2]&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
<pre class="r"><code>bayesplot::mcmc_trace(samples,&quot;beta[1]&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-38-3.png" width="672" /></p>
<p>First of all, is there any evidence that the mean reproduction from
wave sites is different than that of the non-wave sites?</p>
<pre class="r"><code>meanrep_wave = exp(samples$`loga[2]`) * mean(stan_data$DBH) ^ samples$`b[2]`
meanrep_nonwave = exp(samples$`loga[1]`) * mean(stan_data$DBH) ^ samples$`b[1]`

hist(meanrep_nonwave,ylab=&quot;Prob Density&quot;,xlab=&quot;number of cones&quot;,freq = F,xlim=c(25,60),ylim=c(0,0.15),main=&quot;&quot;)
hist(meanrep_wave,density=20,col=&quot;darkgreen&quot;,add=T,freq=F)
legend(&quot;topleft&quot;,col=c(&quot;darkgreen&quot;,&quot;white&quot;),density=c(20,0),legend=c(&quot;wave&quot;,&quot;nonwave&quot;),bty=&quot;n&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>We can use the ‘loo’ package to compute WAIC for this model</p>
<pre class="r"><code># Extract the WAIC for the full model!

library(loo)

loglik_names &lt;- sapply (1:stan_data$N,
                          function(t) sprintf(&quot;log_lik[%s]&quot;,t) )
lls = as.matrix(samples)[,loglik_names]

waic_full = loo::waic(lls)
waic_full$estimates[&quot;waic&quot;,]</code></pre>
<pre><code>##   Estimate         SE 
## 2265.65185   30.71972</code></pre>
<p>Notice that unlike AIC, we not only get a point estimate for WAIC but
we also get a standard error, indicating how sure we are!</p>
<p>An even easier (and probably better) method is to use the LOOIC
metric with pareto smoothed importance sampling (PSIS). This is because
this method provides additional useful diagnostics. Generally WAIC and
LOO-CV/LOOIC will give similar results.</p>
<pre class="r"><code>loo_full &lt;- fit_full$loo()
loo_full</code></pre>
<pre><code>## 
## Computed from 2000 by 242 log-likelihood matrix.
## 
##          Estimate   SE
## elpd_loo  -1132.9 15.4
## p_loo         7.2  1.3
## looic      2265.7 30.7
## ------
## MCSE of elpd_loo is 0.1.
## MCSE and ESS estimates assume MCMC draws (r_eff in [0.6, 1.0]).
## 
## All Pareto k estimates are good (k &lt; 0.7).
## See help(&#39;pareto-k-diagnostic&#39;) for details.</code></pre>
<p>Notice that the LOOIC and WAIC values are nearly identical.</p>
<p>Now let’s build the reduced model and compare LOOIC values!</p>
<pre><code>
data {
  int&lt;lower = 1&gt; N;
  array [N] int&lt;lower=0&gt; obs_cones;
  vector&lt;lower=0&gt; [N] DBH;
}

parameters {
  real loga, b, logbeta;
}

transformed parameters {
  real a = exp(loga);
  real beta = exp(logbeta);
}

model  {
  vector[N] mean_cones = a .* DBH .^ b;   // power function: a*DBH^b
  vector[N] alpha = mean_cones .* beta;
  obs_cones ~ neg_binomial(alpha,beta);
}

generated quantities {   // need log_lik of each data point for model selection
  vector[N] log_lik; // N is the number of data points
  {
    real m2, a2;
    for (n in 1:N) {
       m2 = a * DBH[n]^b;   // power function: a*DBH^b
       a2 = m2 * beta;
       log_lik[n] = neg_binomial_lpmf(obs_cones[n] | a2, beta);
    }
  }
}
</code></pre>
<p>Then we can run the model!</p>
<pre class="r"><code># compile the model using:
firmodel_reduced &lt;- cmdstan_model(&quot;firmodel_reduced.stan&quot;) # Compile stan model

fit_reduced &lt;- suppressMessages( firmodel_reduced$sample(
  data = stan_data,
  chains = 4,
  iter_warmup = 500,
  iter_sampling = 500,
  refresh = 0
)  )</code></pre>
<pre><code>## Running MCMC with 4 parallel chains...
## 
## Chain 1 finished in 1.4 seconds.
## Chain 2 finished in 1.3 seconds.
## Chain 3 finished in 1.5 seconds.
## Chain 4 finished in 1.4 seconds.
## 
## All 4 chains finished successfully.
## Mean chain execution time: 1.4 seconds.
## Total execution time: 1.6 seconds.</code></pre>
<pre class="r"><code># fit_full$summary()
samples_red &lt;- fit_reduced$draws(format=&quot;draws_df&quot;)
bayesplot::mcmc_trace(samples_red,&quot;a&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<pre class="r"><code># bayesplot::mcmc_trace(samples_red,&quot;b&quot;)
# bayesplot::mcmc_trace(samples_red,&quot;beta&quot;)</code></pre>
<p>What is the LOOIC for this model?</p>
<pre class="r"><code># Compute LOOIC

loo_reduced &lt;- fit_reduced$loo()

loo_reduced</code></pre>
<pre><code>## 
## Computed from 2000 by 242 log-likelihood matrix.
## 
##          Estimate   SE
## elpd_loo  -1131.4 15.4
## p_loo         3.9  0.9
## looic      2262.9 30.9
## ------
## MCSE of elpd_loo is 0.1.
## MCSE and ESS estimates assume MCMC draws (r_eff in [0.2, 1.2]).
## 
## All Pareto k estimates are good (k &lt; 0.7).
## See help(&#39;pareto-k-diagnostic&#39;) for details.</code></pre>
<p>Is there a good reason to prefer the full model now?</p>
</div>
<div id="explicit-bayesian-model-selection" class="section level3">
<h3>Explicit Bayesian model selection</h3>
<p>Another cool, sometimes useful, method of Bayesian model selection is
to write the model selection directly into the MCMC algorithm! This
technique, known as reversible jump MCMC (RJMCMC), can be a particularly
elegant way to do model selection. However, this method is not
compatible with HMC, so it is currently not possible to do RJMCMC in
stan.</p>
<p>Here is an example of how to do this in the BUGS language (e.g., that
could be run in JAGS or NIMBLE).</p>
<pre><code>
model  {

  ### Likelihood for model 1: full

  for(i in 1:n.obs){
    expected.cones[i,1] &lt;- a1[wave[i]]*pow(DBH[i],b1[wave[i]])       # a*DBH^b
    spread.cones[i,1] &lt;- r1[wave[i]]
    p[i,1] &lt;- spread.cones[i,1] / (spread.cones[i,1] + expected.cones[i,1])
    observed.cones[i,1] ~ dnegbin(p[i,1],spread.cones[i,1])
    predicted.cones[i,1] ~ dnegbin(p[i,1],spread.cones[i,1])
    SE_obs[i,1] &lt;- pow(observed.cones[i,1]-expected.cones[i,1],2)
    SE_pred[i,1] &lt;- pow(predicted.cones[i,1]-expected.cones[i,1],2)
  }
  
  
  ### Priors, model 1
  for(j in 1:2){   # estimate separately for wave and non-wave
    a1[j] ~ dunif(0.001,2)
    b1[j] ~ dunif(0.5,4)
    r1[j] ~ dunif(0.5,5)
  }

  ### Likelihood for model 2: reduced

  for(i in 1:n.obs){
    expected.cones[i,2] &lt;- a2*pow(DBH[i],b2)       # a*DBH^b
    spread.cones[i,2] &lt;- r2
    p[i,2] &lt;- spread.cones[i,2] / (spread.cones[i,2] + expected.cones[i,2])
    observed.cones[i,2] ~ dnegbin(p[i,2],spread.cones[i,2])
    predicted.cones[i,2] ~ dnegbin(p[i,2],spread.cones[i,2])
    SE_obs[i,2] &lt;- pow(observed.cones[i,2]-expected.cones[i,2],2)
    SE_pred[i,2] &lt;- pow(predicted.cones[i,2]-expected.cones[i,2],2)
  }
  
  
  ### Priors, model 2
  a2 ~ dunif(0.001,2)
  b2 ~ dunif(0.5,4)
  r2 ~ dunif(0.5,5)

  ### Likelihood for model 3: constant a and b

  for(i in 1:n.obs){
    expected.cones[i,3] &lt;- a3*pow(DBH[i],b3)       # a*DBH^b
    spread.cones[i,3] &lt;- r3[wave[i]]
    p[i,3] &lt;- spread.cones[i,3] / (spread.cones[i,3] + expected.cones[i,3])
    observed.cones[i,3] ~ dnegbin(p[i,3],spread.cones[i,3])
    predicted.cones[i,3] ~ dnegbin(p[i,3],spread.cones[i,3])
    SE_obs[i,3] &lt;- pow(observed.cones[i,3]-expected.cones[i,3],2)
    SE_pred[i,3] &lt;- pow(predicted.cones[i,3]-expected.cones[i,3],2)
  }
  
  SSE_obs[1] &lt;- sum(SE_obs[,1]) 
  SSE_pred[1] &lt;- sum(SE_pred[,1])
  SSE_obs[2] &lt;- sum(SE_obs[,2]) 
  SSE_pred[2] &lt;- sum(SE_pred[,2])
  SSE_obs[3] &lt;- sum(SE_obs[,3]) 
  SSE_pred[3] &lt;- sum(SE_pred[,3])

  ### Priors, model 3
  for(j in 1:2){   # estimate separately for wave and non-wave
    r3[j] ~ dunif(0.5,5)
  }
  a3 ~ dunif(0.001,2)
  b3 ~ dunif(0.5,4)

  #####################
  ### SELECT THE BEST MODEL!!! 
  #####################

  for(i in 1:n.obs){
    observed.cones2[i] ~ dnegbin(p[i,selected],spread.cones[i,selected])
    predicted.cones2[i] ~ dnegbin(p[i,selected],spread.cones[i,selected])     # for posterior predictive check!
    SE2_obs[i] &lt;- pow(observed.cones2[i]-expected.cones[i,selected],2)
    SE2_pred[i] &lt;- pow(predicted.cones2[i]-expected.cones[i,selected],2)
  }
  
  SSE2_obs &lt;- sum(SE2_obs[])
  SSE2_pred &lt;- sum(SE2_pred[])


  ### Priors
  
    # model selection...
  prior[1] &lt;- 1/3
  prior[2] &lt;- 1/3     # you can put substantially more weight because fewer parameters (there are more rigorous ways to do this!!)
  prior[3] &lt;- 1/3
  selected ~ dcat(prior[])   
  
  
}
    </code></pre>
<div id="evaluate-model-fit" class="section level4">
<h4>Evaluate model fit</h4>
<p>Now we can look at model fit! We will use the same method we used in
lab- the posterior predictive check…</p>
<p>We can write a for loop to extract the prediction results for each
model (and for the model-averaged model):</p>
<p>First let’s just look at the model predictions vs the observed data.
First, model 1</p>
<pre class="r"><code># Goodness of fit

N &lt;- stan_data$N

plot(fir$TOTCONES~fir$DBH,ylim=c(0,900),cex=2)

# which.max(stan_data$DBH)
# which.min(stan_data$DBH)

a_param &lt;- samples_red$a
b_param &lt;- samples_red$b
beta_param &lt;- samples_red$beta
mu_rep &lt;- sapply(1:N,function(t) a_param * stan_data$DBH[t]^b_param)

sim_dat &lt;- function(s){
  thismean = mu_rep[s,]
  thisbeta &lt;- samples_red$beta[s]
  thisalpha &lt;- thismean * thisbeta 
  thismu = thisalpha / thisbeta
  rnbinom(N,size=thisalpha,mu=thismu)
}

nMCMC = length(samples_red$b)

for(d in 1:N){
  dat= sim_dat(sample(1:nMCMC,1))
  points(stan_data$DBH,dat,pch=20,col=&quot;gray&quot;,cex=0.4)
}
points(fir$DBH,fir$TOTCONES,cex=2)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>Let’s run a Bayesian p-value check for the reduced model:</p>
<pre class="r"><code># Posterior Predictive Checks!

nreps = 500 
SSE_obs= numeric(nreps)
SSE_sim = numeric(nreps)
r=1
for(r in 1:nreps){
  this= sample(1:nMCMC,1,replace = T)
  SSE_obs[r] = sum((stan_data$obs_cones - mu_rep[this,])^2)
  simdat = sim_dat(this)
  SSE_sim[r] = sum((simdat - mu_rep[this,])^2)
}

plot(SSE_sim~SSE_obs,xlab=&quot;SSE, real data&quot;,ylab=&quot;SSE, simulated data&quot;,main=&quot;Posterior Predictive Check&quot;)
abline(0,1,col=&quot;red&quot;)</code></pre>
<p><img src="LECTURE8_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<pre class="r"><code>p.value=mean(SSE_sim&gt;SSE_obs)
p.value </code></pre>
<pre><code>## [1] 0</code></pre>
<p>Interesting- the model seems to not fit very well! It’s possible I
made a coding error somewhere, so if I were doing this analysis for
real, I would triple check everything. If this result holds I might try
to find a better model specification!</p>
<p>Okay, one more topic before we end:</p>
</div>
</div>
<div id="model-averaging" class="section level3">
<h3>Model averaging</h3>
<p>The fact that model selection is such a big deal in ecology and
environmental science indicates that we are rarely certain about which
model is the best model. Even after constructing an AIC table we may be
very unsure about which model is the “true” model.</p>
<p>The AIC weights tell us in essence how much we “believe” in each
model. This is a very Bayesian interpretation, and in general model
averaging really is best thought of in a Bayesian context.</p>
<p>One way to do model averaging relies on AIC weights. Basically we
take the set of predictions from each model independently and weight
them by the Akaike weight. There is a literature on this and R packages
for helping (see package <a
href="https://cran.r-project.org/web/packages/AICcmodavg/AICcmodavg.pdf">‘AICcmodavg’</a>)</p>
<div id="when-should-you-use-model-averaged-parameter-estimates"
class="section level4">
<h4>When should you use model-averaged parameter estimates?</h4>
<p>Really never in my opinion- model averaging can be useful for
prediction but not useful (even misleading) if you are trying to
estimate effect sizes! The reason for this is that due to
multicollinearity, the meaning of parameters can change depending on
which other parameters are in the model. For more info see this paper by
Brian Cade: <a
href="https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/14-1639.1"
class="uri">https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/14-1639.1</a>.</p>
</div>
</div>
<div id="regularization" class="section level3">
<h3>Regularization</h3>
<p>In machine learning and statistics, many methods have a tendency to
over-learn the data- that is, to “learn” random noise and interpret it
as a true signal. Regularization allows us to penalize complexity in our
models, which makes our models skeptical of increased complexity.
Essentially regularization raises the bar for determining whether or not
to make a model more complex. The complexity penalties in AIC and BIC
are examples of regularization in this sense.</p>
<p>In many classical and machine learning methods, we simply add a term
to our likelihood function that penalizes complexity, which forces our
optimizers to choose simpler models unless the data strongly support
adding more complexity.</p>
<p>In Bayesian models, we can bake this skepticism right into our
priors. For example, we can make all our priors on regression
coefficients centered on zero, and with most prior weight in the
neighborhood of zero. In the absence of strong information in the data,
our model will assume that the coefficient is around zero.</p>
<p>It is often difficult to estimate the penalty parameters, so one
common technique is to fit the model with a range of penalty terms and
use cross validation to determine the appropriate penalty term to
use.</p>
<p>If we have time, and there is interest, we can try a worked example
of this technique in class or lab later this semester.</p>
</div>
<div id="causal-inference" class="section level3">
<h3>Causal Inference</h3>
<p>It is important to note that all the model selection techniques we’ve
talked about so far are based on the principle of parsimony- which in
turn is based on the idea of not over-fitting our model to the data –
which in turn is based on the idea that for a model to be ‘useful’ it
should be able to make good predictions for new observations that are
not in the training set. This prediction-centered way of evaluating
model performance makes sense when our goal is to build a predictive
model. But it doesn’t really make sense when the goal is to test causal
hypotheses - that is, when we want to ask questions about “why” and
“how” our outcome is the way it is. When we are trying to test causal
hypotheses, we might sidestep everything in this lecture entirely!
Instead we should draw a DAG and think hard about which variables we
need to include in the model (the ‘adjustment set’) that properly
controls for confounders and gives us the best possible estimate of the
causal effect of A on B.</p>
<p><a href="LECTURE9.html">–go to next lecture–</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
