<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Mixed Effects Modelling</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NRES 746</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Schedule
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="schedule.html">Course Schedule</a>
    </li>
    <li>
      <a href="Syllabus.pdf">Syllabus</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="INTRO.html">Introduction to NRES 746</a>
    </li>
    <li>
      <a href="LECTURE1.html">Why focus on algorithms?</a>
    </li>
    <li>
      <a href="LECTURE2.html">Working with probabilities</a>
    </li>
    <li>
      <a href="LECTURE3.html">The Virtual Ecologist</a>
    </li>
    <li>
      <a href="LECTURE4.html">Likelihood</a>
    </li>
    <li>
      <a href="LECTURE5.html">Optimization</a>
    </li>
    <li>
      <a href="LECTURE6.html">Bayesian #1: concepts</a>
    </li>
    <li>
      <a href="LECTURE7.html">Bayesian #2: mcmc</a>
    </li>
    <li>
      <a href="LECTURE8.html">Model Selection</a>
    </li>
    <li>
      <a href="LECTURE9.html">Performance Evaluation</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lab exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="LAB_Instructions.html">Instructions for Labs</a>
    </li>
    <li>
      <a href="FINALPROJ.html">Final project overview</a>
    </li>
    <li>
      <a href="LAB3demo.html">Lab 3: Likelihood (intro)</a>
    </li>
    <li>
      <a href="LAB5.html">Lab 5: Model selection (optional)</a>
    </li>
    <li>
      <a href="FigureDemo.html">Demo: Figures in R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Student-led topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="LECTURE10.html">Machine Learning</a>
    </li>
    <li>
      <a href="TimeSeries_all.html">Time Series</a>
    </li>
    <li>
      <a href="SCR.html">Spatial Capture-Recapture</a>
    </li>
    <li>
      <a href="spatial_autocorrelation.html">Spatial Autocorrelation</a>
    </li>
    <li>
      <a href="MEM2.html">Mixed Effects Models</a>
    </li>
    <li>
      <a href="MANOVA.html">MANOVA</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data sets
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="TreeData.csv">Tree Data</a>
    </li>
    <li>
      <a href="ReedfrogPred.csv">Reed Frog Predation Data</a>
    </li>
    <li>
      <a href="ReedfrogFuncresp.csv">Reed Frog Func Resp</a>
    </li>
  </ul>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Mixed Effects Modelling</h1>
<h4 class="date">Fall 2021</h4>

</div>


<pre class="r"><code>#_____________________________________#
#     NRES 746, Fall 2021             #
#     Diethelm, McKinnon, Mizell     #
#     University of Nevada, Reno      #
#_____________________________________#


#_____________________________________#
####  Mixed Effects Models  (MEMs) ####
#_____________________________________#</code></pre>
<p>Here is the download link for the R script for this lecture: <a href="MEM2.R">Mixed Effects Models script</a></p>
<div id="mixed-effects-models-mems-what-are-they-anyway" class="section level2">
<h2>Mixed effects models (MEMs): What are they anyway?</h2>
<p>Mixed effects models are a class of models that build on linear models or generalized linear models, with observations measured within discrete groups. These models take into account various factors common in ecological data such as non-independence, heterogeneity, and non-linearity.</p>
<p>While there are no hard and fast rules for how to conduct mixed models, we will be providing some guidelines. We will also attempt to define the required jargon, despite the these definitions being highly contested.</p>
<p>There are two types of effects in mixed modeling:</p>
<ol style="list-style-type: decimal">
<li><p>Random effects are the discrete groupings which are variable or the source of random variability within the dataset. These are often factors that represent a random factor sampled of a larger population (such as field sites, genotype, temporal blocks used in a study).</p></li>
<li><p>Fixed effects are constant and the factors that are directly measured in the experiment, but can have multiple levels.</p></li>
</ol>
</div>
<div id="why-use-mems" class="section level2">
<h2>Why use MEMs?</h2>
<p>Many models or statistical tests have underlying assumptions of independence. Non-independence within or among your data can lead to errors in modelling and skew your results. Mixed models can allow you to explicitly model the lack of independence in the data. Furthermore, using random effects can deal with issues of pseudoreplication.</p>
<p>Non-independent data includes: time series, repeated measurements from same specimens, hierarchical data, longitudinal data, as well as blocked experiments</p>
<p>Example (from Harrison et al. 2018 PeerJ):</p>
<ul>
<li><p>If we measured several chicks from the same clutch, and several clutches from different females, or repeated measurements of the same chick’s growth rate over time, then we have a time series of non-independent data.</p></li>
<li><p>We may expect that measurements within a statistical unit (a female’s clutch) might be more similar than measurements from different units. We can account for this by using the parent ID or chick ID as a random variable in a mixed model.</p></li>
</ul>
<p><img src="Chicks.JPG" /></p>
<p>Under the same idea of accounting for non-independence, your parameter estimate will be more accurate. Specifically, how the model treats the predictors is different for fixed and random effects (hold on for now we’ll explain this in depth later with actual data).</p>
<p>There are also some cons to using MEMs. For instance, there are issues with convergence, predictions for random effects is tricky, there is some difficulty in interpreting the model output due the complexity of the model, and finally you can not directly test a hypothesis that groups are different if they are treated as random effects (you only get one variance estimate).</p>
</div>
<div id="when-to-use-a-random-effect" class="section level2">
<h2>When to use a random effect?</h2>
<p>Random effects are useful when you want to quantify the variability across groups, make predictions for unobserved groups, or combine information across groups.</p>
<p>They can represent a grouping that was randomly sampled from a larger population, a categorical variable that needs to be accounted for but is not a treatment variable (e.g., subject identity, site location, time) &gt; 4 groups (fitting the standard deviation requires at least 3 individuals per level), or unbalanced groups.</p>
<p>Random effects allow for <strong>shrinkage</strong>:</p>
<ul>
<li><p>The estimate of the effect for each group computed from a linear mixed model is “pushed” towards the grand mean effect compared to when we fit a separate linear model to each group’s data.</p></li>
<li><p>Group-level estimates are shrunk towards the mean slope. The less data we have from a given subject, the greater the shrinkage or partial pooling.</p></li>
<li><p>This means that the group’s effect estimate will be based on the more abundant data, this also helps with unbalanced datasets.</p></li>
</ul>
</div>
<div id="what-packages-are-available-in-r-for-mems" class="section level2">
<h2>What packages are available in R for MEMs?</h2>
<p><strong>lme4</strong> An older modeling system and has less tools. Some suggests this is better with temporal data</p>
<p><strong>nlme</strong> New modeling system and has large toolbox than lme4 and offers ability to make models more complex</p>
<p><strong>glmmTMB</strong> For zero inflated data, when you have many zeros such as in surveys or for specific model comparisons (more on that later)</p>
</div>
<div id="syntax-for-mems" class="section level2">
<h2>Syntax for MEMs:</h2>
<p>Random (non-fixed) intercept only model:</p>
<p>mixed_model_intercept &lt;- lmer(Response ~ Fixed_Predictor + (1|Random_Predictor), data = data, REML = FALSE)</p>
<p>Random (non-fixed) slope and intercept model:</p>
<p>mixed_model_intercept&amp;slope &lt;- lmer(Response ~ Fixed_Predictor + (1+ Fixed_Predictor|Random_Predictor), data = data, REML = FALSE)</p>
<p>mixed_model_intercept&amp;slope &lt;- lmer(Response ~ Fixed_Predictor + (Fixed_Predictor|Random_Predictor), data = data, REML = FALSE)</p>
<p><em>We’ll show this with actual data and graphs shortly.</em></p>
</div>
<div id="general-approach-and-steps-to-using-mems" class="section level2">
<h2>General approach and steps to using MEMs:</h2>
<ol style="list-style-type: decimal">
<li>Start with data exploration and looking at patterns in the data</li>
</ol>
<ul>
<li>Begin with the most complex model and test (include interactions, random intercept, etc) by creating other models that are less complex</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Run models and look at their AIC, BIC, and LogLik scores using anova(model 1, model 2….model n)</li>
</ol>
<ul>
<li>Lower values are better for AIC and BIC (with less than 2 unit differences models are considered to be equally good)</li>
<li>Similarly, LogLik is negative so less negative values are better</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Check models for convergence</li>
</ol>
<ul>
<li>If there are convergence issues then scaling or centering the covariances may help</li>
<li>Or, use the simplified model instead</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Explore models that remain for their basic residual distributions using plot(model) and other functions, testing their validity, and exploring any warnings</li>
</ol>
<p><em>Some argument to always center your data and residuals, bolker mentioned running only adjusted residuals in his models</em></p>
</div>
<div id="load-example-dataset" class="section level2">
<h2>Load example dataset:</h2>
<pre class="r"><code>##load packages
library(lme4) 
library(nlme)
library(glmmTMB)
library(ggplot2)</code></pre>
<pre class="r"><code>##RIKZ dataset

#as described in Zuur et al. (2007) and Zuur et al. (2009)

##download data to follow along:

#rikz_data &lt;- &quot;https://uoftcoders.github.io/rcourse/data/rikz_data.txt&quot;

#download.file(rikz_data, &quot;rikz_data.txt&quot;)

rikz_data  &lt;- read.table(&quot;rikz_data.txt&quot;, header = TRUE, sep=&quot;\t&quot;)</code></pre>
</div>
<div id="explanation-of-the-data-set" class="section level2">
<h2>Explanation of the data set:</h2>
<p>There are 9 intertidal areas (denoted ‘Beach’)</p>
<p>At each beach the researchers sampled five sites (denoted ‘Site’)</p>
<p>Research also noted abiotic variables (exposure and NAP) and calculated the species richness of macro-fauna</p>
<p>‘Richness’ refers to the total number of aquatic invertebrate species found at a given site</p>
<p>‘NAP’ refers to the height of the sampling location relative to the mean sea level.</p>
<p>‘Exposure’ refers to physical components of the site as experienced by the macro-fauna as example wave action and length of surf zone</p>
<p><strong>Our question is: “What is the influence of NAP on species richness?”</strong></p>
<p><img src="Beach%20example.JPG" /></p>
</div>
<div id="modeling-the-data" class="section level2">
<h2>Modeling the data:</h2>
<pre class="r"><code>rikz_data$Beach &lt;- as.factor(rikz_data$Beach)
str(rikz_data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    45 obs. of  5 variables:
##  $ Richness: int  11 10 13 11 10 8 9 8 19 17 ...
##  $ Exposure: int  10 10 10 10 10 8 8 8 8 8 ...
##  $ NAP     : num  0.045 -1.036 -1.336 0.616 -0.684 ...
##  $ Beach   : Factor w/ 9 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 1 2 2 2 2 2 ...
##  $ Site    : int  1 2 3 4 5 1 2 3 4 5 ...</code></pre>
<pre class="r"><code>##This code is adapted from: https://uoftcoders.github.io/rcourse/lec08-linear-mixed-effects-models.html#accounting_for_non-independence

# Start with a linear model:
lm1 &lt;- lm(Richness~ NAP, data = rikz_data)
summary(lm1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Richness ~ NAP, data = rikz_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.0675 -2.7607 -0.8029  1.3534 13.8723 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.6857     0.6578  10.164 5.25e-13 ***
## NAP          -2.8669     0.6307  -4.545 4.42e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.16 on 43 degrees of freedom
## Multiple R-squared:  0.3245, Adjusted R-squared:  0.3088 
## F-statistic: 20.66 on 1 and 43 DF,  p-value: 4.418e-05</code></pre>
<p>Coming back to our question “How does NAP influence species richness”, NAP does appear to be significantly associated with richness based on the model output above.</p>
<p>But, first we have to check that the model is fitting the data.</p>
<p>Let’s start with diagnostic plots for the residuals against the fitted values and a QQ-plot.</p>
<pre class="r"><code># Check model assumptions.
par(mfrow=c(2,2))
plot(lm1)</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#The QQ plot looks okay, but first panel suggests that the model assumption for
#homogeneity is violated.

#Here we see an increasing variance in the residuals with increasing fitted
#values.

#For now, we will ignore these violations of the model assumptions to explore
#mixed-effects modelling strategies on untransformed data.

#Furthermore, we also know the observations in these data are not independent.</code></pre>
<p>Now let’s look at beach as a fixed predictor to illustrate why it’s better as a random effect:</p>
<pre class="r"><code>lm2 &lt;- lm(Richness ~ NAP + Beach, data = rikz_data)
summary(lm2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Richness ~ NAP + Beach, data = rikz_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8518 -1.5188 -0.1376  0.7905 11.8384 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   9.8059     1.3895   7.057 3.22e-08 ***
## NAP          -2.4928     0.5023  -4.963 1.79e-05 ***
## Beach2        3.0781     1.9720   1.561  0.12755    
## Beach3       -6.4049     1.9503  -3.284  0.00233 ** 
## Beach4       -6.0329     2.0033  -3.011  0.00480 ** 
## Beach5       -0.8983     2.0105  -0.447  0.65778    
## Beach6       -5.2231     1.9682  -2.654  0.01189 *  
## Beach7       -5.4367     2.0506  -2.651  0.01196 *  
## Beach8       -4.5530     1.9972  -2.280  0.02883 *  
## Beach9       -3.7820     2.0060  -1.885  0.06770 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.06 on 35 degrees of freedom
## Multiple R-squared:  0.7025, Adjusted R-squared:  0.626 
## F-statistic: 9.183 on 9 and 35 DF,  p-value: 5.645e-07</code></pre>
<p>The model is estimating a separate effect for each beach (with 8 total as 1 is used as the reference). This is drastically reducing our degrees of freedom, which gives less ability to detect relationships that exist.</p>
<p>However, we need to account for non-independence among sites within a beach, so let’s try putting beach as a random effect.</p>
<p>First, we will build the simpler intercept-only model and then a model where the slopes are allowed to vary as the more complicated model.</p>
<pre class="r"><code>#Q: What is the influence of NAP on species richness, while accounting for
#variation within beaches?

# Although a Poison might work well here given that richness a count of species,
# we will use a Gaussian distribution to keep things simple

#The (1|Beach) is the random effect term, where the 1 denotes this is a
#random-intercept model and the term on the right of the | is a nominal variable
#(or factor) to be used as the random effect.

#This model is fit using maximum likelihood, rather than restricted maximal
#likelihood by specifying REML = FALSE

#If your data are balanced (i.e., similar sample sizes in each factor group) and
#your random effects are not nested, then you can set REML to FALSE to use
#maximum likelihood.


mem.intercept &lt;- lmer(Richness ~ NAP + (1|Beach), data = rikz_data, REML = FALSE)

summary(mem.intercept)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Richness ~ NAP + (1 | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    249.8    257.1   -120.9    241.8       41 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.4258 -0.5010 -0.1791  0.2452  4.0452 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Beach    (Intercept) 7.507    2.740   
##  Residual             9.111    3.018   
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   6.5844     1.0321   6.380
## NAP          -2.5757     0.4873  -5.285
## 
## Correlation of Fixed Effects:
##     (Intr)
## NAP -0.164</code></pre>
<p>Notice the model out includes an estimated variance for the random effects in the model.</p>
<p>Here, the variance associated with the effect of beach is ~7.5.</p>
<p>We can look at the total amount of variance by summing all the variance including the residuals. Then we can see that by including beach as a random effect we are accounting for ~45% of the total unexplained variance (that which is not from our fixed effect of NAP).</p>
<p>In other words, differences between beaches account for (7.507 / 7.507 + 9.111) * 100 = 45% of the residual variance after accounting for the fixed effects in the model. This is a large effect that would have gone unaccounted for if we didn’t include beach in model.</p>
<p>Note: the estimate or beta-coefficient for NAP has changed with our new model.</p>
<p>Let’s visual the model now:</p>
<pre class="r"><code># Let&#39;s plot the linear model for each beach, with a varying intercept only: 
rikz_data$fit_mem.intercept &lt;- predict(mem.intercept)

ggplot(rikz_data, aes(x = NAP, y = Richness, colour = Beach)) +
    # Add fixed effect regression line (i.e. NAP)
    geom_abline(aes(intercept = `(Intercept)`, slope = NAP),
                size = 2,
                as.data.frame(t(fixef(mem.intercept)))) +
    # Add fitted values (i.e. regression) for each beach
    geom_line(aes(y = fit_mem.intercept), size = 1) +
    geom_point(size = 3) +
    theme_classic() +
    theme(legend.position = &quot;none&quot;) +
    scale_colour_brewer(palette=&quot;Set1&quot;)</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-8-1.png" width="90%" /></p>
<p>The black line shows the fitted values associated with the fixed-effect component of the model.</p>
<p>The other lines show the fitted values estimated for each beach.</p>
<p>Now let’s look at the model with a random slope and intercept:</p>
<pre class="r"><code># Random intercept and slope model
mem_intslope &lt;- lmer(Richness ~ NAP + (1 + NAP|Beach), REML = FALSE,
                             data = rikz_data)</code></pre>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<pre class="r"><code>summary(mem_intslope)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Richness ~ NAP + (1 + NAP | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    246.7    257.5   -117.3    234.7       39 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7985 -0.3418 -0.1827  0.1749  3.1389 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  Beach    (Intercept) 10.949   3.309         
##           NAP          2.502   1.582    -1.00
##  Residual              7.174   2.678         
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   6.5818     1.1883   5.539
## NAP          -2.8293     0.6849  -4.131
## 
## Correlation of Fixed Effects:
##     (Intr)
## NAP -0.810
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<p>Here there is an additional variance component in the random effects, which estimates the variance in slopes across beaches.</p>
<p>Furthermore, now that beach is allowed to vary in response to NAP using a random intercept and slope model, beach is accounting for ~52% of the total variance not explained by the fixed effect of NAP.</p>
<p>We did have some convergence issues with this model, however we are ignoring those for now and would suggest scaling the variables and re-running these models. We think it’s best to just move forward with this demo for the sake of time.</p>
<pre class="r"><code># Let&#39;s plot the linear model for each beach, with a varying intercept AND slope: 
rikz_data$fit_IntSlope &lt;- predict(mem_intslope)

ggplot(rikz_data, aes(x = NAP, y = Richness, colour = Beach)) +
    geom_abline(aes(intercept = `(Intercept)`, slope = NAP),
                size = 2,
                as.data.frame(t(fixef(mem_intslope)))) +
    geom_line(aes(y = fit_IntSlope), size = 1) +
    geom_point(size = 3) +
    theme_classic() +
    theme(legend.position = &quot;none&quot;) +
    scale_colour_brewer(palette=&quot;Set1&quot;)</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-10-1.png" width="90%" /></p>
<p>Here you can see that the beaches with larger intercepts also have more steeply negative slopes. In addition, the regression line now fits the data points better.</p>
<p>Now that you understand the workings of the models and how parameter estimates can vary by model, let’s talk more about selecting your random effects.</p>
<p>Recall that setting beach as a fixed effect resulted in the model estimating a separate parameter for each beach, which gobbled up degrees of freedom.</p>
<p>While it is important to use the knowledge of your dataset when selecting a random effect, if we wanted to test for model differences the glmmTMB package will allow us to do this. Recall that the glmmTMB package was designed for zero-inflated countdata (i.e., data containing more zeros than would be expected from the standard error distributions in other mixed models). Models that ignore zero-inflation, or treat it like overdispersion, tend to resulted in biased parameter estimates (Harrison, 2014).</p>
<p>Here though, we will use the glmmTMB package because it is the only MEM package that allows us to create a regression both with and without a random effect.</p>
<pre class="r"><code>mod1 &lt;- glmmTMB(Richness ~ NAP, data = rikz_data)
mod2 &lt;- glmmTMB(Richness ~ NAP + (1|Beach), data = rikz_data)

#The relative fit of two nested models can be evaluated using a chi-square difference statistic:
anova(mod1, mod2, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Data: rikz_data
## Models:
## mod1: Richness ~ NAP, zi=~0, disp=~1
## mod2: Richness ~ NAP + (1 | Beach), zi=~0, disp=~1
##      Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(&gt;Chisq)    
## mod1  3 259.95 265.37 -126.98   253.95                             
## mod2  4 249.83 257.06 -120.92   241.83 12.124      1  0.0004977 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The Chi-sq test suggests that the model 2 is the better model between the two being investigated.</p>
<p>Recall that using the principle of parsimony we are looking for the model with the largest degree of explanatory power with as few predictor variables as possible. The Chi-square difference tests essentially tell us whether the extra predictors or interactions really improve the model. This form of model selection can only be used when comparing nested models (i.e., models that share predictors in a nested fashion). It is also worth noting that the ‘anova()’ tests the models against one another in the order specified.</p>
<p>Next, let’s take a look at including a random slope and intercept in the model and see if that would improve our fit.</p>
<p>We can compare our mixed models using the Akaike Information Criterion, AIC (Akaike, 1998) metric:</p>
<pre class="r"><code>#First we want to try scaling our numeric predictor to help with convergence
NAP.sc &lt;- scale(rikz_data$NAP, center = TRUE, scale = TRUE)

#this function calculates the mean and standard deviation of the entire vector,
#then scales each element by those values by subtracting the mean and dividing
#by the sd.

#REML=FALSE is particularly important for linear mixed model selection
mod5 &lt;- lmer(Richness ~ NAP.sc  + (1|Beach), REML=FALSE, data = rikz_data)
summary(mod5)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Richness ~ NAP.sc + (1 | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    249.8    257.1   -120.9    241.8       41 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.4258 -0.5010 -0.1791  0.2452  4.0452 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Beach    (Intercept) 7.507    2.740   
##  Residual             9.111    3.018   
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   5.6889     1.0181   5.588
## NAP.sc       -2.5610     0.4846  -5.285
## 
## Correlation of Fixed Effects:
##        (Intr)
## NAP.sc 0.000</code></pre>
<pre class="r"><code>#AIC = 249.8

mod6 &lt;- lmer(Richness ~ NAP.sc + (1 + NAP|Beach), REML=FALSE, data = rikz_data)</code></pre>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<pre class="r"><code>summary(mod6)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Richness ~ NAP.sc + (1 + NAP | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    246.7    257.5   -117.3    234.7       39 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7985 -0.3418 -0.1827  0.1749  3.1389 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  Beach    (Intercept) 10.949   3.309         
##           NAP          2.502   1.582    -1.00
##  Residual              7.174   2.678         
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   5.5981     1.0052   5.569
## NAP.sc       -2.8132     0.6811  -4.131
## 
## Correlation of Fixed Effects:
##        (Intr)
## NAP.sc -0.720
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<pre class="r"><code>#AIC = 246.7

anova(mod5, mod6)</code></pre>
<pre><code>## Data: rikz_data
## Models:
## mod5: Richness ~ NAP.sc + (1 | Beach)
## mod6: Richness ~ NAP.sc + (1 + NAP | Beach)
##      npar    AIC    BIC  logLik deviance Chisq Df Pr(&gt;Chisq)  
## mod5    4 249.83 257.06 -120.92   241.83                      
## mod6    6 246.66 257.50 -117.33   234.66 7.173  2    0.02769 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The Chi-sq test does suggest that random slope and intercept model fit the data better than our other model, but we should check our residuals to see how the model is doing:</p>
<pre class="r"><code># we still need check model fit
plot(residuals(mod6))</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-13-1.png" width="70%" /></p>
<pre class="r"><code>qqnorm(resid(mod6))# QQ-plot
qqline(resid(mod6))</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-13-2.png" width="70%" /></p>
<p>This could be better and we are still having convergence issues with the more complex model (despite scaling the NAP predictor).</p>
<p>Let’s try using a generalized linear mixed model with a poisson family since richness is a count of species present (i.e., count data).</p>
<pre class="r"><code>#REML=FALSE does not work in generalized linear mixed model selection
#glmer() uses Maximum Likelihood (ML) as default rather than Restricted Maximum Likelihood (REML)

mod7 &lt;- glmer(Richness ~ NAP.sc  + (1|Beach), family = poisson, data = rikz_data)
summary(mod7)</code></pre>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: poisson  ( log )
## Formula: Richness ~ NAP.sc + (1 | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    220.8    226.2   -107.4    214.8       42 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.9648 -0.6155 -0.2243  0.2236  3.1869 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  Beach  (Intercept) 0.2249   0.4743  
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.48715    0.17603   8.448  &lt; 2e-16 ***
## NAP.sc      -0.50102    0.07492  -6.687 2.28e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## NAP.sc 0.162</code></pre>
<pre class="r"><code>#AIC = 220.8

mod8 &lt;- glmer(Richness ~ NAP.sc + (1 + NAP|Beach), family = poisson, data = rikz_data)
summary(mod8)</code></pre>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: poisson  ( log )
## Formula: Richness ~ NAP.sc + (1 + NAP | Beach)
##    Data: rikz_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    218.7    227.8   -104.4    208.7       40 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.35846 -0.51127 -0.21845  0.09802  2.45384 
## 
## Random effects:
##  Groups Name        Variance Std.Dev. Corr
##  Beach  (Intercept) 0.2630   0.5128       
##         NAP         0.0891   0.2985   0.18
## Number of obs: 45, groups:  Beach, 9
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   1.4830     0.1983   7.479 7.48e-14 ***
## NAP.sc       -0.6039     0.1366  -4.421 9.81e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## NAP.sc 0.354</code></pre>
<pre class="r"><code>#AIC = 218.7

anova(mod7, mod8)</code></pre>
<pre><code>## Data: rikz_data
## Models:
## mod7: Richness ~ NAP.sc + (1 | Beach)
## mod8: Richness ~ NAP.sc + (1 + NAP | Beach)
##      npar    AIC    BIC  logLik deviance Chisq Df Pr(&gt;Chisq)  
## mod7    3 220.78 226.20 -107.39   214.78                      
## mod8    5 218.74 227.78 -104.37   208.74 6.043  2    0.04873 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Based on these tests, we can see that the random slope and intercept model fit the data better than our other model, even with the penalties that come with a more complex model.</p>
<pre class="r"><code># we still need check model fit
plot(residuals(mod8))</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-15-1.png" width="70%" /></p>
<pre class="r"><code>qqnorm(resid(mod8))# QQ-plot
qqline(resid(mod8))</code></pre>
<p><img src="MEM2_files/figure-html/unnamed-chunk-15-2.png" width="70%" /></p>
<p>It took us a while to find the optimal model to fit the data, but it was worth it.</p>
<p>While using an intercept-only random effect is easier and much more common, the rationale for this should come from the data themselves and not the level of difficulty.</p>
</div>
<div id="further-resources" class="section level2">
<h2>Further Resources</h2>
<p>Lastly we want to leave you with resources to further investigate mixed effects modelling</p>
<ul>
<li><p>Analysing Ecological Data 2007, Zuur, Leno and Smith Mixed Model Chapter (“Mixed Effects Modelling for Nested Data” Pg 101-142)</p></li>
<li><p>Mixed Effects Models and Extensions in Ecology with R 2009 Zuur et al. <a href="https://unr.primo.exlibrisgroup.com/permalink/01UNR_INST/146dp7v/alma991013777570306781" class="uri">https://unr.primo.exlibrisgroup.com/permalink/01UNR_INST/146dp7v/alma991013777570306781</a></p></li>
<li><p>gethub info on mixed effects N.D. Shrikanth S <a href="https://ademos.people.uic.edu/Chapter17.html" class="uri">https://ademos.people.uic.edu/Chapter17.html</a></p></li>
<li><p>Generalized linear mixed models: a practical guide for ecology and evolution <a href="https://www.sciencedirect.com/science/article/pii/S0169534709000196" class="uri">https://www.sciencedirect.com/science/article/pii/S0169534709000196</a></p></li>
<li><p>An Introduction to Linear Mixed-Effects Modeling in R 2021 Brown VA<br />
<a href="https://journals.sagepub.com/doi/full/10.1177/2515245920960351" class="uri">https://journals.sagepub.com/doi/full/10.1177/2515245920960351</a></p></li>
<li><p>A brief introduction to mixed effects modelling and multi-model inference in ecology 2018 Harrison et al. <a href="https://peerj.com/articles/4794/" class="uri">https://peerj.com/articles/4794/</a></p></li>
<li><p>Quantitative Methods in R for Biology N.D. Santangelo JS <a href="https://uoftcoders.github.io/rcourse/lec08-linear-mixed-effects-models.html" class="uri">https://uoftcoders.github.io/rcourse/lec08-linear-mixed-effects-models.html</a></p></li>
<li><p>Bolker github FAQ <a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html" class="uri">https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html</a></p></li>
</ul>
<p>— the End —</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
