---
output:
  word_document: default
  pdf_document: default
---

**NRES 746 -- Workout of the Day #1: Math & Stats Self-Diagnostic**

This is **not graded and will not be collected**. There are no wrong answers -- the goal
is just to take stock of the tools you're bringing into this class, and to see which
ones might need a bit of dusting off. Some of these are meant to make you think a
little! Keep this sheet; we'll refer back to it later in the semester.

**Instructions:** Work alone for about 5 minutes. Don't worry if you get stuck --
just note where you got stuck and move on. After 5 minutes, compare answers with a
neighbor for a few minutes.

## Part 1: Logarithms & exponents ---------------------------------

**1a.** Solve for x: $2^x = 32$

x = _______________

**1b.** A population grows according to $N_t = N_0 e^{rt}$. If $N_0 = 100$ and
$N_t = 550$ after $t = 8$ years, solve for the growth rate $r$:

_______________________________________________________________________________

_______________________________________________________________________________

r = _______________________________________________

## Part 2: Derivatives & integrals ---------------------------------

**2a.** If $f(x) = (4x^2 - 3x)^5$, what is $f'(x)$?

_______________________________________________________________________________

_______________________________________________________________________________

$f'(x) =$ _______________________________________________

**2b.** A recruitment rate for a population is given by $r(t) = 4t$ (new individuals per unit time).
Compute the total number of new recruits between $t=0$ and $t=5$:

_______________________________________________________________________________

_______________________________________________________________________________

$\displaystyle\int_0^5 4t \, dt =$ _______________________________________________

## Part 3: Probability ---------------------------------

**3a.** $P(A) = 0.4$, $P(B) = 0.5$, and $P(A \text{ and } B) = 0.2$. What is
$P(A \text{ or } B)$?

_______________________________________________________________________________

_______________________________________________________________________________

**3b.** A family has two children. You are told that at least one of them is a girl.
What is the probability that *both* children are girls? Briefly show your reasoning
(consider all the equally likely possibilities for two children).

_______________________________________________________________________________

_______________________________________________________________________________

_______________________________________________________________________________

**3c.** What if I reworded the above question... You are now told: A family has two children. You go to their home and observed a girl playing in the backyard. What is the probability that *both* children are girls? Does this wording change your answer from above?

_______________________________________________________________________________

_______________________________________________________________________________

_______________________________________________________________________________


## Part 4: Confidence intervals & p-values ---------------------------------

**4a.** Circle the interpretation you think is *most correct* for a 95% confidence
interval on a mean:

  a) There is a 95% probability that the true mean falls within this particular interval.
  b) If we repeated this study many times, about 95% of the intervals we compute would contain the true mean.
  c) 95% of the data fall within this interval.

**4b.** Circle the definition you think is *most correct* for a p-value:

  a) The probability that the null hypothesis is true.
  b) The probability of observing results at least as 'extreme' under the null hypothesis.
  c) The probability that the alternative hypothesis is false.

## Part 5: R / pseudocode ---------------------------------

**5.** Write a function `GetCV()` that computes the coefficient of variation
(standard deviation divided by the mean) of a numeric vector `x`. You can use
`sd()` and `mean()`.

```
GetCV <- function(x){


}
```

## Self-rating ---------------------------------

For each part above, circle how confident you felt (1 = totally lost, 5 = very confident):

| Part                  | 1 | 2 | 3 | 4 | 5 |
|------------------------|---|---|---|---|---|
| Logs & exponents        | o | o | o | o | o |
| Derivatives/integrals    | o | o | o | o | o |
| Probability             | o | o | o | o | o |
| Confidence intervals/p-values | o | o | o | o | o |
| R / pseudocode          | o | o | o | o | o |
